### ISSUE TITLE
nucleotide CDS alignment (MSA) file of release 3.9.0

### ISSUE THREAD

**Issue by akhats** [ANHIG/IMGTHLA#113]
I want to download the multiple sequence alignment files of release 3.9.0 release because we want to finish the remaining portion of an old project. However, I am unable to find the those files in this repository. Specifically I need the file DQA_nuc.txt or DQA1_nuc.txt for release 3.9.0. as I already have the files of other genes I am interested in. 

Let me know if there is anyway I can find that file.

Thank you

**Comment by ANHIG** [comment]
The files requested can be found in the alignments sub-directory, here is a direct link

https://github.com/ANHIG/IMGTHLA/blob/390/alignments/DQA_nuc.txt
