### ISSUE TITLE
Some alleles are missing from hla.xml

### ISSUE THREAD

**Issue by legezam** [ANHIG/IMGTHLA#114]
Hi

During my recent investigation, i found that some alleles are missing from hla.xml which are in hla.dat. For example, HLA-H*02:06. There are ~300 alleles in this situation.

Is this intended?

Thank you,
Marcell

**Comment by ANHIG** [comment]
The hla.dat file contains all alleles in the IPD-IMGT/HLA Database, at the current time the hla.xml is restricted to the expressed HLA genes. This is the cause of the discrepancy.


________________________________

**Comment by legezam** [comment]
Thank you for your answer. Is this going to change in the near future?

**Comment by ANHIG** [comment]
We will be looking to add the remaining genes in the future.

________________________________

**Comment by legezam** [comment]
Thank you!
