### ISSUE TITLE
Extra sequence information for C*04:09N

### ISSUE THREAD

**Issue by rleonid** [ANHIG/IMGTHLA#116]
I think theres an extra "ATGTGT" at the end C_nuc.fasta, at least with comparison to the sequence in the alignment file.

**Comment by ANHIG** [comment]
Thank you for bringing this discrepancy to our attention.  The C*04:09N sequence we hold in the database appears to be correct, however this error has occurred in the specific marking up of the CDS sequence in the nuc.fasta.  The sequence following the stop codon in the fasta is genomic sequence.  This appears to be a long standing issue and we appreciate your assistance in identifying it.
