### ISSUE TITLE
Inconsistent knowledge for DPB1*01:01:01

### ISSUE THREAD

**Issue by rleonid** [ANHIG/IMGTHLA#117]
Alignment (alignments/DPB_nuc.txt) implies that we don't have sequence information for the final alanine, but the fasta (fasta/DPB_nuc.fasta) has it.

**Comment by ANHIG** [comment]
Can you please confirm the alleles and branch the files are found in. The latest release has two alleles matching DPB1*01:01:01 (DPB1*01:01:01:01 and DPB1*01:01:01:02) and the alignment file is now named DPB1_nuc.txt. Reviewing these files the DPB1_nuc.txt and DPB1_nuc.fasta appear consistent for these alleles.

**Comment by rleonid** [comment]
My apologies, I meant allele `DPB1*13:01:02`. I erred in my copy-and-pasting. Yes, I'm using `DPB1*01:01:01:01` as the reference allele. The difference is between the `DPB1_nuc.txt` or `DPB1_nuc.fasta` files.

For example,  the last part of the alignment file for the reference and the allele:

> $ grep -E "DPB1\*01:01:01:01|DPB1\*13:01:02" alignments/DPB1_nuc.txt | tail -n 2
DPB1*01:01:01:01  AAG AAA G|TT CAA CGA GGA TCT GCA TAA
DPB1*13:01:02     --- --- -|-- --- --- --- --- --- --*

Sorry, but the font sizes won't line up. The last line of `DPB1*13:01:02`'s fasta entry:

> $ gawk 'BEGIN { RS=">" }; /DPB1\*13:01:02/{printf RS; printf $0}' fasta/DPB1_nuc.fasta  | tail -n 1
GGAGTGGGCATCTTCATGCACAGGAGGAGCAAGAAAGTTCAACGAGGATCTGCATAA

**Comment by ANHIG** [comment]
We are currently looking to see if this discrepancy is in any of the other formats. Once this is compete, we will look at applying an update to the necessary files.

**Comment by jrob119** [comment]
This should be addressed in the latest release (3.31.0)
