### ISSUE TITLE
Sequence length error found for DRB1*14:13 (HLA00845)

### ISSUE THREAD

**Issue by cfrangus** [ANHIG/IMGTHLA#120]
For DRB1*14:13 (HLA00845) We noticed that the exon regions do not match the overall sequence length.  As you can see from this snippet, the sequence length is 687 but the actual sequence listed is only 549 in length.
FT   exon            1..270
FT                   /number="2"
FT   exon            271..549
FT                   /number="3"
FT   exon            553..663
FT                   /number="4"
FT   exon            664..687
FT                   /number="5"
SQ   Sequence 687 BP; 152 A; 173 C; 223 G; 139 T; 0 other;
     cacgtttctt ggagtactct acgtctgagt gtcatttctt caatgggacg gagcgggtgc        60
     ggttcctgga gagatacttc cataaccagg aggagaacgt gcgcttcgac agcgacgtgg       120
     gggagtaccg ggcggtgacg gagctggggc ggcctagcgc cgagtactgg aacagccaga       180
     aggacctcct ggagcagagg cgggccgcgg tggacaccta ctgcagacac aactacgggg       240
     ttggtgagag cttcacagtg cagcggcgag tccatcctaa ggtgactgtg tatccttcaa       300
     agacccagcc cctgcagcac cacaacctcc tggtctgttc tgtgagtggt ttctatccag       360
     gcagcattga agtcaggtgg ttccggaatg gccaggaaga gaagactggg gtggtgtcca       420
     caggcctgat ccacaatgga gactggacct tccagaccct ggtgatgctg gaaacagttc       480
     ctcggagtgg agaggtttac acctgccaag tggagcaccc aagcgtgaca agccctctca       540
     cagtggaat                                                               549

**Comment by ANHIG** [comment]
Many thanks for reporting this, we will look into what has caused this issue.


On 21 Nov 2017, at 17:19, cfrangus <notifications@github.com<mailto:notifications@github.com>> wrote:


For DRB1*14:13 (HLA00845) We noticed that the exon regions do not match the overall sequence length. As you can see from this snippet, the sequence length is 687 but the actual sequence listed is only 549 in length.
FT exon 1..270
FT /number="2"
FT exon 271..549
FT /number="3"
FT exon 553..663
FT /number="4"
FT exon 664..687
FT /number="5"
SQ Sequence 687 BP; 152 A; 173 C; 223 G; 139 T; 0 other;
cacgtttctt ggagtactct acgtctgagt gtcatttctt caatgggacg gagcgggtgc 60
ggttcctgga gagatacttc cataaccagg aggagaacgt gcgcttcgac agcgacgtgg 120
gggagtaccg ggcggtgacg gagctggggc ggcctagcgc cgagtactgg aacagccaga 180
aggacctcct ggagcagagg cgggccgcgg tggacaccta ctgcagacac aactacgggg 240
ttggtgagag cttcacagtg cagcggcgag tccatcctaa ggtgactgtg tatccttcaa 300
agacccagcc cctgcagcac cacaacctcc tggtctgttc tgtgagtggt ttctatccag 360
gcagcattga agtcaggtgg ttccggaatg gccaggaaga gaagactggg gtggtgtcca 420
caggcctgat ccacaatgga gactggacct tccagaccct ggtgatgctg gaaacagttc 480
ctcggagtgg agaggtttac acctgccaag tggagcaccc aagcgtgaca agccctctca 540
cagtggaat 549

**Comment by ANHIG** [comment]
Can you confirm which release version this issue is seen in. We have checked the latest release and the HLA00485 entry for DRB1*14:13, contains 687 bases, as indicated by the coordinates.

**Comment by cfrangus** [comment]
This occurred in both 3.29.0 and 3.29.0.1 releases

**Comment by ANHIG** [comment]
Thanks for the clarification, from release 3.30 onwards, we have changed the methods used to build these files to try and resolve a number of issues, primarily related to the sequence feature co-ordinates. This issue should be resolved in releases 3.30 onwards.

**Comment by cfrangus** [comment]
Ok, thanks.  Do you plan to release an updated version of 3.29?

**Comment by ANHIG** [comment]
The individual entry has been updated, but the bug may be seen in other sequences.

**Comment by cfrangus** [comment]
OK.  Thank you for your help.
