### ISSUE TITLE
C*17:01:01:02

### ISSUE THREAD

**Issue by vineeth-s** [ANHIG/IMGTHLA#133]
Hi James,

During the processing of a bunch of new alleles, we ran into an issue with C*17:01:01:02
The hla.dat file we pulled from the git repository has Exon 5 marked as "pseudo" while on the IPD-IMGT/HLA website it is not marked as such. A cursory look at the history of the sequence does not indicate any recent changes. We were wondering if this was intentional and something we should take into account in our work flow ?

Cheers,
Vineeth

**Comment by jrob119** [comment]
The pseudo tag is new, and intended for DQB1 and KIR alleles, we will look at why the C*17 allele is marked up as described.

**Comment by jrob119** [comment]
Update added to remove erroneous pseudo tags
