### ISSUE TITLE
Genomic alignment of DPA1*04:01 and DPA1*04:02 in the DPA1_gen.txt file

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#135]
The alignment in the DPA1_gen.txt file for DPA1 *04:01 and *04:02 makes it appear that these alleles differ significantly in their sequence for positions 1061 to 1093, as below.

![dpa1_gen_0401-0402_intron1](https://user-images.githubusercontent.com/8935284/37801762-0665644c-2de5-11e8-8372-c7cede21dec5.png)

However, the sequences of these alleles are identical through these positions, and it seems like the sequence for *04:02 should only include a 3 nucleotide deletion, relative to the reference, for positions 1061 - 1063, as below.

![dpa1_gen_0401-0402_intron1_fixed](https://user-images.githubusercontent.com/8935284/37802462-c6ce520a-2de7-11e8-9672-c59d7b440087.png)

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention.  An updated version of the DPA1_gen.txt file will be available in the upcoming release which will improve the alignment.
