### ISSUE TITLE
Incorrectly using join for DRB5 sequences in 3.20.0 and 3.21.0

### ISSUE THREAD

**Issue by mhalagan** [ANHIG/IMGTHLA#136]
In the **hla.dat** files for **3.20.0** and **3.21.0** a `join` is being used for the CDS sequence when it shouldn't be which causes parsers to fail. Here's an example:

```
DR   EMBL; AJ427352; AJ427352.1.
XX
FH   Key             Location/Qualifiers
FH
FT   source          1..270
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /db_xref="taxon:9606"
FT                   /ethnic="Caucasoid"
FT                   /cell_line="Barpay"
FT   CDS             join(1..270)
FT                   /codon_start=1
FT                   /partial
FT                   /gene="HLA-DRB5"
FT                   /allele="HLA-DRB5*01:12"
FT                   /product="MHC Class II HLA-DRB5*01:12 sequence"
FT                   /translation="RFLQQDKYECHFFNGTERVRFLHRDIYNQEEDLRFDSDVGEYRAV
FT                   TELGRPDAESWNSQKDFLERRRAEVDTVCRHNYGVGESFTVQRR"
```

Should be `FT   CDS             1..270` or `FT   CDS             <1..270>` instead.

Here's a list of all the alleles that have this:

HLA01638.1 HLA-DRB5\*01:11
HLA01634.1 HLA-DRB5\*01:12
HLA01871.1 HLA-DRB5\*01:13
HLA00927.1 HLA-DRB5\*02:03
HLA00928.1 HLA-DRB5\*02:04
HLA01280.1 HLA-DRB5\*02:05
HLA00916.1 HLA-DRB5\*01:01:02
HLA00918.2 HLA-DRB5\*01:03
HLA00920.1 HLA-DRB5\*01:05
HLA00921.1 HLA-DRB5\*01:06
HLA00922.1 HLA-DRB5\*01:07
HLA00924.1 HLA-DRB5\*01:09
HLA01012.3 HLA-DRB5\*01:10N

**Comment by jrob119** [comment]
Single feature joins have been removed from the DRB5 allele entries
