### ISSUE TITLE
Invalid character � in dat file for 3.21.0, 3.22.0, 3.23.0 and 3.24.0

### ISSUE THREAD

**Issue by mhalagan** [ANHIG/IMGTHLA#137]
The following line is found in the hla.dat file for 3.21.0, 3.22.0, 3.23.0 and 3.24.0.
```
RA   Balas A, S�nchez-Gordo F, Garcia-S�nchez F, Gomez-Zumaquero JM, Vicario JL;
```

This prevents these files from being properly parsed.

Here are the specific alleles that have this issue:

Release = 3210, line # = 121045, Allele = HLA-A\*11:210N
Release = 3210, line # = 177260, Allele = HLA-A\*26:107N
Release = 3220, line # = 125142, Allele = HLA-A\*11:210N
Release = 3220, line # = 183644, Allele = HLA-A\*26:107N
Release = 3230, line # = 127802, Allele = HLA-A\*11:210N
Release = 3230, line # = 187727, Allele = HLA-A\*26:107N
Release = 3240, line # = 129967, Allele = HLA-A\*11:210N
Release = 3240, line # = 191426, Allele = HLA-A\*26:107N

**Comment by jrob119** [comment]
The files have been corrected to include an 'a' instead of the previous character
