### ISSUE TITLE
hla.xml 3.32.0 HLA-C*02:10:01:01  <hla_g_group status="C*02:10:01GG"/>

### ISSUE THREAD

**Issue by mallen2** [ANHIG/IMGTHLA#140]
Greetings, 

Allele HLA-C*02:10:01:01 has an extra 'G' <hla_g_group status="C*02:10:01GG"/> in hla.xml for 3.32.0. 
 
May the force be with you,
Marney

 <allele id="HLA02120" name="HLA-C*02:10:01:01" dateassigned="2005-02-18">
    <releaseversions firstreleased="2.9.0" lastupdated="3.10.0" currentrelease="3.32.0" releasestatus="Sequence unchanged" confirmed="Confirmed"/>
    <locus genesystem="HLA" locusname="HLA-C" hugogenename="HLA-C" class="I" />
    <cwd_catalogue cwd_status="Common" cwd_version="2.0.0" cwd_reference="http://doi.org/10.1111/tan.12093"/>
    <hla_g_group status="C*02:10:01GG"/>
    <hla_p_group status="C*02:02P"/>

**Comment by jrob119** [comment]
The xml file has been updated to address this, and changes made to both branch 3.32.0 and Latest
