### ISSUE TITLE
incorrect/missing alignmentreference elements in hla.xml

### ISSUE THREAD

**Issue by j-hn** [ANHIG/IMGTHLA#143]
For the DPB1 alleles, the alignmentreference element attributes have an empty alleleid attribute, and the allelename attribute contains "DPB1*01:01:01", but the allele element in the file has the extended name "DPB1*01:01:01:01" so the reference is not made.

DRBx alleles also have an empty alleleid alignmentreference attribute, but in these cases the DRB1*01:01:01 allele is named consistently

john

**Comment by jrob119** [comment]
The elements have been corrected to ensure the allele IDs are present in both the DPB1 and relevant DRB genes
