### ISSUE TITLE
Identical sequences with different feature annotations -  174 alleles

### ISSUE THREAD

**Issue by mhalagan** [ANHIG/IMGTHLA#150]
Feature annotations should not differ between database releases if the sequence is the same. If an annotation is changed in a later database release, then it should also be updated in all previous database releases that contain that sequence. **_The feature annotations for 174 alleles change between database releases even though the sequences do not._** These differences mainly impact intron-4, exon-5, and intron-5 for HLA-DQB1. Below is a table of all the observed instances of this issue. 

| DB   | Allele               | # Features Removed | # Features Added | # Features Differ | Features Removed | Features Added  | Features that Differ |
|------|----------------------|--------------------|------------------|-------------------|------------------|-----------------|----------------------|
| 3160 | HLA-B*15:302N        | 0                  | 0                | 3                 |                  |                 | exon_5 exon_2 exon_3 |
| 3160 | HLA-C*08:89N         | 0                  | 0                | 1                 |                  |                 | exon_2               |
| 3170 | HLA-B*15:302N        | 0                  | 0                | 1                 |                  |                 | exon_5               |
| 3180 | HLA-B*39:97N         | 0                  | 0                | 1                 |                  |                 | exon_3               |
| 3180 | HLA-C*08:89N         | 0                  | 0                | 1                 |                  |                 | exon_2               |
| 3190 | HLA-C*08:89N         | 0                  | 0                | 1                 |                  |                 | exon_2               |
| 3220 | HLA-B*07:251N        | 0                  | 0                | 1                 |                  |                 | exon_3               |
| 3280 | HLA-B*15:149N        | 0                  | 0                | 1                 |                  |                 | exon_4               |
| 3280 | HLA-B*15:246N        | 0                  | 0                | 1                 |                  |                 | exon_4               |
| 3280 | HLA-C*08:89N         | 0                  | 0                | 1                 |                  |                 | exon_2               |
| 3290 | HLA-B*15:149N        | 0                  | 0                | 1                 |                  |                 | exon_4               |
| 3290 | HLA-B*15:246N        | 0                  | 0                | 1                 |                  |                 | exon_4               |
| 3300 | HLA-A*24:155N        | 1                  | 0                | 0                 | exon_5           |                 |                      |
| 3300 | HLA-A*26:01:01:03N   | 0                  | 0                | 2                 |                  |                 | intron_4 exon_4      |
| 3300 | HLA-B*07:44N         | 0                  | 0                | 2                 |                  |                 | intron_4 exon_4      |
| 3300 | HLA-B*15:01:01:02N   | 0                  | 1                | 1                 |                  | exon_1          | intron_1             |
| 3300 | HLA-B*15:149N        | 0                  | 0                | 1                 |                  |                 | exon_4               |
| 3300 | HLA-B*15:246N        | 0                  | 0                | 2                 |                  |                 | exon_5 exon_4        |
| 3300 | HLA-B*44:02:01:02S   | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:01:01    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:02:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:02:04    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:53Q      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:62       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:79       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:80       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:81       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:82       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:83       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:84       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*02:96N      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:03 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:04 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:05 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:06 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:07 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:08 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:09 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:10 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:11 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:12 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:14 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:15 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:16 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:17 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:01:18 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:17    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:22    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:35    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:36    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:01:37    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:01:03 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:09    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:12    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:21    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:22    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:23    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:02:24    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:03:02:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:03:02:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:03:02:03 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:03:04    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:04:01    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:04:03    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:05:01    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:150      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:191      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:195      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:196      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:197Q     | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:19:01    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:211      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:239      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:243      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:245      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:246      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:247      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:248      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:249      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:250      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:251      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:252      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:253      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:254      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*03:263      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*04:01:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*04:02:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*04:02:11    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*04:02:12    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*04:11       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*04:32       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:01:03 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:01:04 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:01:05 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:23    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:01:24    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:02:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:02:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:02:01:03 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:02:07    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:02:11    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:102      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:103      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:104      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:106      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:108      | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3300 | HLA-DQB1*05:133      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:134      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:135      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:136      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:137      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:148      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:149      | 1                  | 1                | 0                 | exon_6           | exon_5          |                      |
| 3300 | HLA-DQB1*05:31       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:43:02    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:52       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:57       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*05:96       | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3300 | HLA-DQB1*05:97       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:01:08    | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3300 | HLA-DQB1*06:01:10    | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3300 | HLA-DQB1*06:01:11    | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3300 | HLA-DQB1*06:02:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:01:03 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:17    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:22    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:23    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:25    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:26    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:27    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:02:28    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:12    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:14    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:20    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:21    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:23    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:24    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:25    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:03:26    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:04:01    | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:09:01:01 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:09:01:02 | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:103      | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3300 | HLA-DQB1*06:111      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:117      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:125      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:187      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:188      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:217      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:218      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:219      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:221      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:222      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:223      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:224      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:225      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:226      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:227      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:228      | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:37       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:44       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:84       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:90       | 0                  | 2                | 1                 |                  | exon_5 intron_5 | intron_4             |
| 3300 | HLA-DQB1*06:99:02    | 0                  | 1                | 1                 |                  | exon_5          | exon_6               |
| 3320 | HLA-C*07:02:01:17N   | 0                  | 0                | 2                 |                  |                 | intron_3 exon_3      |

**Comment by jrob119** [comment]
Thanks for reporting these inconsistencies, we are reviewing the output and will be checking the latest release first for any corrections, and then will look at the feasibility of updating previous releases.

**Comment by jrob119** [comment]
The descriptions of null alleles and in particular those with indels, can be subject to change as the we look at implementing new feature qualifiers. The example given includes HLA-DQB1 where the non-expressed exon 5 sequence is now marked up rather than be included in intron. This is an example of where changing the description adds information but does cause a discrepancy between versions.
