### ISSUE TITLE
Error in Sequence tag

### ISSUE THREAD

**Issue by MarkusFuhrmann** [ANHIG/IMGTHLA#151]
Hi James,

in the new release 3.33.0 of hla.dat some DRB1 sequences are invalid. See for example DRB1*13:09, the substring "y/alignment_libraries/libs/drb1345genomiclib:drb1_13:09" should not be there, i think.

FH   Key             Location/Qualifiers
FH
FT   source          1..325
FT                   /organism="Homo sapiens"
FT                   /mol_type="genomic DNA"
FT                   /db_xref="taxon:9606"
FT                   /ethnic="Hispanic"
FT                   /cell_line="MJD"
FT                   /cell_line="NT01111"
FT   CDS             <1..270
FT                   /codon_start=1
FT                   /partial
FT                   /gene="HLA-DRB1"
FT                   /allele="HLA-DRB1*13:09"
FT                   /product="MHC Class II HLA-DRB1*13:09 sequence"
FT                   /translation="RFLEYSTSECHFFNGTERVRFLDRYFHNQEENVRFDSDVGEFRAV
FT                   TELGRPDAEYWNSQKDILEQARAAVDTYCRHNYGVVESFTVQRR"
FT   exon            1..270
FT                   /number="2"
FT   UTR             271..328
SQ   Sequence 325 BP; 58 A; 67 C; 100 G; 51 T; 49 other;
     cacgtttctt ggagtactct acgtctgagt gtcatttctt caatgggacg gagcgggtgc        60
     ggttcctgga cagatacttc cataaccagg aggagaacgt gcgcttcgac agcgacgtgg       120
     gggagttccg ggcggtgacg gagctggggc ggcctgatgc cgagtactgg aacagccaga       180
     aggacatcct ggagcaggcg cgggccgcgg tggacaccta ctgcagacac aactacgggg       240
     ttgtggagag cttcacagtg cagcggcgag y/alignmen t_librarie s/libs/drb       300
     1345genomi clib:drb1_ 13:09                                             325
//

Cheers,
Markus

**Comment by jrob119** [comment]
This issue has been fixed, in an update posted 16th July
