### ISSUE TITLE
C*02:10:01GG

### ISSUE THREAD

**Issue by mallen2** [ANHIG/IMGTHLA#153]
Hi all,

This extra G is causing us some issues.

allele id="HLA18583" name="HLA-C*02:02:37" dateassigned="2018-03-29"
    hla_g_group status="C*02:10:01**GG**"
    hla_p_group status="C*02:02P"

Thank you!
Marney

**Comment by jrob119** [comment]
Corrected, and hla.xml re-compressed and will be uploaded shortly.
