### ISSUE TITLE
DQA1*05:01:04 is not in P or G group in hla.xml.

### ISSUE THREAD

**Issue by mallen2** [ANHIG/IMGTHLA#155]
Good morning again,

We noticed an inconsistency between the files. Will you correct which ever needs to be corrected, please? 

allele id="HLA18836" name="HLA-DQA1*05:01:04" dateassigned="2018-04-30"
    hla_g_group status="None"/
    hla_p_group status="None"/

hla_nom_g.txt
DQA1*;05:01:01:01/05:01:01:02/05:01:01:03/**05:01:04**/05:03:01:01/05:03:01:02/05:05:01:01/05:05:01:02/05:05:01:03/05:05:01:04/05:05:01:05/05:05:01:06/05:05:01:07/05:05:01:08/05:05:01:09/05:05:01:10/05:06:01:01/05:06:01:02/05:07/05:08/05:09/05:11;05:01:01G

DQA1*;05:01:01:01/05:01:01:02/05:01:01:03/05:01:02/**05:01:04**/05:03:01:01/05:03:01:02/05:05:01:01/05:05:01:02/05:05:01:03/05:05:01:04/05:05:01:05/05:05:01:06/05:05:01:07/05:05:01:08/05:05:01:09/05:05:01:10/05:06:01:01/05:06:01:02/05:07/05:08/05:09/05:11;05:01P

Thank you!
May the force be with you,
Marney

**Comment by jrob119** [comment]
Corrected, and hla.xml re-compressed and will be uploaded shortly.
