### ISSUE TITLE
Comma in Description field of Deleted_alleles.txt file

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#159]
Line 106 of the Deleted_alleles.txt file (`HLA00615,DQA1*05013,To take account of coding polymorphism in the leader peptide, sequence renamed DQA1*05:05 (April 1998)`) includes a comma in the Description field. 

This results in an extra column being added for this line when parsing the file as a .csv document. 

Could this comma be removed? It doesn't change the meaning of the entry.

**Comment by jrob119** [comment]
Extra comma removed
