### ISSUE TITLE
Assembly version

### ISSUE THREAD

**Issue by srx3001** [ANHIG/IMGTHLA#161]
Hello all,

I am working on a neoantigene pipeline and using optitype for HLA detection. Optitype has an older FASTA version (2013) and the same alleles differ.
What is the assembly version of the most recent FASTA  files here (2018)? I am looking at hla_nuc.fasta and hla_prot.fasta. GRCH39/HG39?
I was unable to find the info in readme/version report/change log, nor is it at
https://www.ebi.ac.uk/ipd/imgt/hla/ .
I think it would be useful to have it somewhere clearly visible.

Thank you

**Comment by jrob119** [comment]
The IPD-IMGT/HLA Database is independent of the GRCH39/HG39 builds and as such do not map to these directly, or have an assembly version linked to these.
