### ISSUE TITLE
Problems with the 3.34.0 nuc.txt and prot.txt alignments for HLA-B and -C

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#163]
In the 3.34.0 [HLA-B protein alignment](https://github.com/ANHIG/IMGTHLA/blob/Latest/alignments/B_prot.txt), the `HLA-B*13:120Q` peptide sequence is 11 amino acids longer than the reference, but these positions are not accounted for in the reference with `.` symbols. As a result, even though the last sequence block for all other alleles only include 69 amino-acid positions, the last 11 amino acids of the `HLA-B*13:120Q` sequence appear in a separate block, as below.
![screen shot 2018-10-17 at 3 08 17 pm](https://user-images.githubusercontent.com/8935284/47119455-c1150700-d21f-11e8-8402-d499182cb809.png)

This also occurs for the B_nuc.txt alignment, as below. 
![screen shot 2018-10-17 at 3 08 43 pm](https://user-images.githubusercontent.com/8935284/47119503-e99d0100-d21f-11e8-977e-31c9d4a0d52b.png)

The same thing is also true for the `C*04:09N` allele in the C_prot.txt and C_nuc.txt alignments.

It seems like these extra peptide positions should be included in the reference sequences as sequence indels.

**Comment by jrob119** [comment]
As identified the same applies for the C*04:09N, in order to minimise characters and formatting, the additional bases for these alleles have been entered as a single extra line. This is consistent between these two alleles and other past releases. We are aware this may cause issues if attempting to parse the text files however we strongly advise the use of other standardised formats for any data imports.

**Comment by sjmack** [comment]
Unlike the additional bases and peptide residues for `C*04:09N`, the number of the additional sequences for `B*13:23Q` is non-sequential from the final position of all the other HLA-B alleles. 

![screen shot 2018-10-29 at 2 15 49 pm](https://user-images.githubusercontent.com/8935284/47682140-b7c55c00-db88-11e8-9cf0-7e18980e9f84.png)
![screen shot 2018-10-29 at 2 15 59 pm](https://user-images.githubusercontent.com/8935284/47682169-cc095900-db88-11e8-96b2-f12fb833543a.png)
The final amino acid residue coordinate for every other allele is 338, but the coordinates for the additional peptide sequence for `B*13:23Q` begin at 363, which is 338 + 24, the length of the leader peptide sequence. Shouldn't these start at 339, the way that the coordinates for the extra peptide sequence for `C*04:09N` start with 343?

There are similar numbering discrepancies for the `B*13:23Q` nucleotide sequence in the B_nuc.txt file.

**Comment by sjmack** [comment]
This problem for the HLA-B alignment (reported above on Oct, 29 2018) has reoccurred with version 3.35.0.

In addition, the renumbering of the additional sequence for B*13:123Q in the 3.34.0 alignment, appears to treat the insertion sequence in the reference as a peptide position. 

![HLA-B_3 34 0](https://user-images.githubusercontent.com/8935284/54802465-a577b780-4c28-11e9-9520-36169dce8e03.png)
Compare this to the numbering of the additional sequence for C*04:09, relative to the longer insertion in the reference, which is not treated as a peptide position or positions. 
![HLA-C_3 33 0](https://user-images.githubusercontent.com/8935284/54802468-aa3c6b80-4c28-11e9-8a2c-92a78bddf56c.png)

**Comment by jrob119** [comment]
We will investigate and update as needed, apologies

**Comment by dominicbarkerAN** [comment]
This will be corrected in the upcoming release 3.36.0 due on 17 April 2019.
