### ISSUE TITLE
incomplete fasta file

### ISSUE THREAD

**Issue by afadda91** [ANHIG/IMGTHLA#166]
hi,
the hla_gen.fasta from the latest version contains sequences for only 5773 alleles.
where are the other alleles? can't find DPA1*03:02 for instance.

thanks,

**Comment by dominicbarkerAN** [comment]
The hla_gen.fasta only contains the sequences of alleles which have a full length sequence.  We consider a full length sequence to be from the start codon to the stop codon including all exons and introns.  However in order for a sequence to received an official allele name we only require the exons which code for the antigen recognition site.  Therefore many sequences in the database are partial and these partial sequences are not in the individual gen.fasta or hla_gen.fasta.  DPA1*03:02 for example only has sequence for exon 2.  It will therefore not appear in the hla_gen.fasta.
