### ISSUE TITLE
Urgent issues with zip files

### ISSUE THREAD

**Issue by lrschroer** [ANHIG/IMGTHLA#170]
The following url - https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/xml/hla.xml.zip is broken - it provides corrupted ZIP file (1KB size). 

Other urls seem to be working – e.g. https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/wmda/hla_nom.txt 

Could you please take a look at this and fix the zip files? We would appreciate the help ASAP as this is blocking our processing of the latest release.

**Comment by jrob119** [comment]
Due to the increasing file sizes for the hla.dat and some of the compressed zip files, the repository now requires the Git LFS tools (https://git-lfs.github.com<https://git-lfs.github.com/>) which handles file over 100MB. Please use these when cloning to ensure the larger files are downloaded correctly. If Git LFS is not used then large files will contain pointers to the Git LFS location rather than the data required.

**Comment by lrschroer** [comment]
Thanks, James. A few additional questions from us:

1.	hla.zml.zip size is just 5MB – how does it relate to the described 100MB issue?

2.	If we download hla.xml.zip via https://github.com/ANHIG/IMGTHLA/raw/Latest/xml/hla.xml.zip (it redirects to https://media.githubusercontent.com/media/ANHIG/IMGTHLA/Latest/xml/hla.xml.zip ) - then the zip file is downloaded successfully. As far as we understand the zip files are now handled via media.githubuserconsent (instead of raw.githubuserconsent) - could you please confirm this? 

3.	We’re using Java HttpClient to download files from https://raw.githubusercontent.com/ANHIG/IMGTHLA/ .   https://git-lfs.github.com/ is just standalone binary. We see the open source git-lfs implementation https://github.com/bozaro/git-lfs-java/ - but it’s not a quick fix to change our code to use it (comparing to just changing url in configuration). Do you have recommendations about this? 

Again, thank you!

**Comment by jrob119** [comment]
Git FLS was introduced to handle the size issues in the unzipped XML and .dat files, which had either exceeded or where close to exceeding the file limits. This would have prevented us from uploading new files. The GitHub website are designed to handled these files but may point to different URLs for the files handled using LFS.  The hla.xml had already had to be zipped as it was close to meeting the size requirements, we can review if this needs to be marked up for downloading/uploading via lfs, as the zip has reduced the size.

I would recommend changing the URL where possible, if this is giving access to the correct zip, ie not the pointer file.
