### ISSUE TITLE
Missing archive zip file

### ISSUE THREAD

**Issue by Rachelmarty20** [ANHIG/IMGTHLA#171]
Hello, 

In the README, you note that a "zip compressed archive of all the text-format alignment files is available from the top-level directory". However, I am unable to find such a zip file. The only zip file appears to be the Alignment_Rel_3350.zip that contains the alignments from the current release. 

In particular, I would like to find archive versions of the alignment files and the archive versions of the fasta files. 

Can you point me in the right direction?

Thanks,
Rachel

**Comment by jrob119** [comment]
The Git has a branch for each release, and latest points to the current version, to find the older versions of the files, please select the appropriate branch.
