### ISSUE TITLE
Strange deletion at A*01:18N peptide position 341

### ISSUE THREAD

**Issue by IHIW** [ANHIG/IMGTHLA#172]
In the [A_prot.txt](https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/A_prot.txt ) alignment, the sequence for the final peptide position for `A*01:18N` is a deletion (`.`), but the sequence for the preceding 158 peptide positions is unknown (`*`). 

This does not correspond to the [A_nuc.txt](https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/A_nuc.txt) alignment, where exon 8 nucleotide sequence is *****.

This terminal deletion does not show up in the .fasta, .msf or .pir alignments (but honestly, it isn't clear how it could).

**Comment by jrob119** [comment]
This is an error, and will be corrected the final '.' should be a '*', I will look at producing an update.

**Comment by dominicbarkerAN** [comment]
This will be corrected in release 3.36.0 due 17 April 2019.
