### ISSUE TITLE
Release 3.36.0 - file inconsistencies

### ISSUE THREAD

**Issue by lrschroer** [ANHIG/IMGTHLA#179]
1. There are two new alleles where "dateassigned" is blank in the hla.xml file, DQA1 05:05:01:20 (HLA22679) and DRB4 01:03:01:10 (HLA22663). The dates are listed appropriately in the hla_nom file. 

2. There is an inconsistency between hla_nom and hla.xml for HLA00886, where the xml file has the allele name as v2 DRB3 010101 while the nom file has v3 DRB3 01:01:01. Could you explain this for us? 

3. The hla.xml file has a G group listed as C*07:726N:01G while nom_g lists it as 07:726:01G. Could you please look into this one too? 

4. There is an inconsistency between nom_p and hla.xml regarding DQA1 05:05:01:20. This allele is listed as part of DQA1*05:01P in nom_p but has no p group status in the xml file. 

Any help on the above is greatly appreciated. Thanks!

**Comment by jrob119** [comment]
This has been addressed in the latest commit.
