### ISSUE TITLE
Fetch latest version number

### ISSUE THREAD

**Issue by benbelow** [ANHIG/IMGTHLA#186]
A feature I'm working on needs to be able to fetch the latest version number of the database. From browsing the repo I can see three ways of finding this out: 

(a) The `Version` header at the top of any `.txt` file, fetched from the `Latest` branch
(b) The file names of the `AlleleNames` files, again from the `Latest` branch
(c) The branch names themselves

I've currently opted for (a), but none feel ideal.

If there is currently a better way of fetching the latest version number programatically, please let me know

If not - is it the case that the version header in the published txt files is going to remain in a consistent format indefinitely? 

And would it be possible / preferable to publish the current version as an independent file?

**Comment by jrob119** [comment]
As identified the current most suitable solutions for retrieving the version numbers are those listed, our preference would be for option (a). This is also the method we have previously advised for other users. 

Please be aware we are currently reviewing how the version numbers are defined and whilst we do not expect any changes, to the first two fields, i.e. 3.37, we cannot guarantee that minor changes may not be made or that the current syntax will remain indefinitely. How and when the version number is incremented beyond the second field is complicated by the volume of files involved and the type of changes. For this reason the commit version can be used to track most minor changes. 

At the current time we have not considered a separate file defining just the the release number.

**Comment by benbelow** [comment]
@jrob119 It transpires that we will instead be aiming to use the *latest but one* release. 

i.e. As 3.37 is the current latest, we would aim to be using 3.36.

Is there a recommended way of finding this out programatically from the repository? The agreed solution (a) above no longer works unless we keep a local store of historic versions.
