### ISSUE TITLE
Corrupt files on branch 320 (release 3.2.0)

### ISSUE THREAD

**Issue by peterjc** [ANHIG/IMGTHLA#189]
It looks like someone accidentally checked in unresolved git merges on branch 320, there are lots of ``<<<<<<< HEAD`` lines:

```
$ git clone https://github.com/ANHIG/IMGTHLA.git
$ cd IMGTHLA
$ git checkout 320
$ cat *.dat | grep -c "<<<<<<<"
19215
$ cat msf/*.msf | grep -c "<<<<<<<"
7930
```

etc - not just those folders affected.

**Comment by jrob119** [comment]
As this release is now over  files are now over 10 years old and files no longer valid for clinically accredited work, I will close the issue.
