### ISSUE TITLE
KW line is different for some DPB1 alleles

### ISSUE THREAD

**Issue by cfrangus** [ANHIG/IMGTHLA#191]
When trying to process the hla.dat file for the 3.37 allele database we noticed that 37 DPB alleles have a different KW format.

Altered format for 37 DPB1 alleles:
KW   Human MHC; HLA; Class II; HLA-DPB1*1001:01; Allele; HLA-DPB1*1001:01;
Format for all other DPB1 alleles:
KW   Human MHC; HLA; Class II; HLA-DPB1; Allele; HLA-DPB1*01:01:01:01;

The following HLAIDs have the altered KW line:
HLA23690
HLA23492
HLA23735
HLA23784
HLA23035
HLA23580
HLA23417
HLA23792
HLA23570
HLA23340
HLA23490
HLA23560
HLA23346
HLA23887
HLA24055
HLA24175
HLA23856
HLA23985
HLA23938
HLA23977
HLA23854
HLA24007
HLA23959
HLA24097
HLA24088
HLA24259
HLA23957
HLA23826
HLA24316
HLA23895
HLA23884
HLA24317
HLA24167
HLA24226
HLA24100
HLA24304
HLA24158

Was this a change by design?

**Comment by cfrangus** [comment]
We've also noticed in the FT /Gene line for these 37 DPB alleles it includes the allele name.  Outside of MICA, other /Gene lines only contain the locus.  Was this also a change by design?

**Comment by jrob119** [comment]
This is an issue for HLA-DPB1 alleles with 4 digit names in the first field i.e. HLA-DPB1*1001:01. The hla.dat file will be updated and the code corrected for the next release.

**Comment by jrob119** [comment]
Issues with git lfs are delaying pushing this update.
