### ISSUE TITLE
TAP1 and TAP2 protein alignments start at position 0 in release 3.37.0

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#192]
The TAP1 and TAP2 protein alignments identify the N-terminal Methionine as position 0, but in the respective nucleotide alignments, the corresponding sequence is correctly identified as codon 1. 

In addition, there is a second pipe above the second amino acid in each protein alignment (see below). 

This is not the case in releases 3.35.0 or 3.36.0. 

![Screen Shot 2019-09-27 at 11 20 04 AM](https://user-images.githubusercontent.com/8935284/65792615-fc4ed400-e118-11e9-9459-ca550ca929bd.png)

![Screen Shot 2019-09-27 at 11 19 53 AM](https://user-images.githubusercontent.com/8935284/65792670-15f01b80-e119-11e9-817a-361774343ca5.png)

**Comment by jrob119** [comment]
This has been corrected in both the txt and zip files.
