### ISSUE TITLE
How can I learn how to parse file like alignments/A_gen.txt

### ISSUE THREAD

**Issue by AEDWIP** [ANHIG/IMGTHLA#194]
I am a student and need to convert an alignment file to vcf. I found https://www.ebi.ac.uk/ipd/imgt/hla/nomenclature/index.html

I am looking for very basic information for example
What does a insert, delete, polymorphism look like

What is the gDNA 500 mean?

Kind regards

Andy

**Comment by jrob119** [comment]
Thanks for your enquiry, the following pages detail the formatting and numbering used in the alignment files. 

https://www.ebi.ac.uk/ipd/imgt/hla/nomenclature/alignments.html
https://www.ebi.ac.uk/ipd/imgt/hla/help/align_help.html
