### ISSUE TITLE
hla.xml release 3.38.0 cannot parse xml, first character is Tab

### ISSUE THREAD

**Issue by bmatern** [ANHIG/IMGTHLA#198]
I downloaded hla.xml.zip for release 3.38.0. The first character is a Tab (indent). This breaks XML parsers.

Deleting the tab resolves the problem.

**Comment by dominicbarkerAN** [comment]
This has now been corrected in the latest commit to the 3.38.0 and Latest branches.  In addition the hla_ambigs.xml has has tab characters converted to spaces to be consistent with the hla.xml file.
