### ISSUE TITLE
why cat all fasta/*_gen.fasta not equal to fasta/hla_gen.fasta?

### ISSUE THREAD

**Issue by yubau1112** [ANHIG/IMGTHLA#205]
why cat all fasta/*_gen.fasta not equal to fasta/hla_gen.fasta?

wc -l  cat_ALL_gen.fasta hla_gen.fasta
  1342528 cat_ALL_gen.fasta
   671264 hla_gen.fasta

What causes the difference?

thanks!

**Comment by jrob119** [comment]
As this is closed, is it now resolved? A cat of *gen.fasta will include the hla_gen.fasta along with the individual gene libraries, which is why they differ.
