### ISSUE TITLE
hla.xml: MICA/MICB alleles prefixed with "HLA-"

### ISSUE THREAD

**Issue by mjoud** [ANHIG/IMGTHLA#206]
The `name`, `locusname` and `hugogenename` attributes for all MICA/MICB alleles in `hla.xml` are erroneously prefixed with `HLA-`.

```xml
  <allele id="HLA01013" name="HLA-MICA*001" expandedname="MICA*001::01:01" dateassigned="1998-10-10">
    <!-- .... -->
    <locus genesystem="HLA" locusname="HLA-MICA" hugogenename="HLA-MICA" class="Class I chain-related gene" />
```

**Comment by dominicbarkerAN** [comment]
Thank you for pointing out this issue. This has now been corrected in the latest release of the database 3.39.0 and is available in the Latest branch.
