### ISSUE TITLE
Deleted_Alleles.txt for 3.39.0 does not rename C*07:226 to C*07:226Q

### ISSUE THREAD

**Issue by mgeorge-nmdp** [ANHIG/IMGTHLA#215]
https://github.com/ANHIG/IMGTHLA/blob/Latest/Deleted_alleles.txt#L180
has
```
HLA07484,C*07:226,Sequence renamed C*07:226 (October 2019)
```
while https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/Allelelist.3390.txt shows
```
HLA07484,C*07:226Q
```

**Comment by jrob119** [comment]
This has been updated in 3.39.0, apologies for the delay
