### ISSUE TITLE
hla.xml.zip for 3.41.0 has invalid XML char

### ISSUE THREAD

**Issue by mgeorge-nmdp** [ANHIG/IMGTHLA#225]
hla.xml contains an invalid character which causes parsing issues.

a Java application reports

>    File hla.xml.zip can not be parsed due to the error: Parsing cannot be performed: 
>    An invalid XML character (Unicode: 0xb) was found in the value of attribute "title" and element is "citation".  
>    Line number: 1266638, column number: 184

xmllint  reports

> hla.xml:1266638: parser error : invalid character in attribute value
> on of two novel HLA-DQB1*05:01:01 variants, identified in Brazilian individuals.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention, these invalid characters have now been removed.
