### ISSUE TITLE
Alleles duplication in IMGT 3.42 hla.xml file

### ISSUE THREAD

**Issue by adeverea** [ANHIG/IMGTHLA#238]
Seems like in 3.42 we have alleles with same id but different data.

 <allele id="HLA00664" name="HLA-DRB1*01:01:01:01" expandedname="DRB1*01:01:01:01" dateassigned="1989-08-01">
    <releaseversions firstreleased="1.0.0" lastupdated="1.1.2" currentrelease="3.42.0" releasestatus="Sequence unchanged" confirmed="Confirmed"/>
    <locus genesystem="HLA" locusname="HLA-DRB1" hugogenename="HLA-DRB1" class="II" />
.......
  <allele id="HLA00664" name="HLA-DRB1*01:01:01:01" expandedname="DRB1*01:01:01:01" dateassigned="1989-08-01">
    <releaseversions firstreleased="1.0.0" lastupdated="1.1.2" currentrelease="3.42.0" releasestatus="Sequence unchanged" confirmed="Confirmed"/>
    <locus genesystem="HLA" locusname="HLA-DRB3" hugogenename="HLA-DRB3" class="II" />
.......
  <allele id="HLA00664" name="HLA-DRB1*01:01:01:01" expandedname="DRB1*01:01:01:01" dateassigned="1989-08-01">
    <releaseversions firstreleased="1.0.0" lastupdated="1.1.2" currentrelease="3.42.0" releasestatus="Sequence unchanged" confirmed="Confirmed"/>
    <locus genesystem="HLA" locusname="HLA-DRB4" hugogenename="HLA-DRB4" class="II" />
.......
  <allele id="HLA00664" name="HLA-DRB1*01:01:01:01" expandedname="DRB1*01:01:01:01" dateassigned="1989-08-01">
    <releaseversions firstreleased="1.0.0" lastupdated="1.1.2" currentrelease="3.42.0" releasestatus="Sequence unchanged" confirmed="Confirmed"/>
    <locus genesystem="HLA" locusname="HLA-DRB5" hugogenename="HLA-DRB5" class="II" />

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention. The duplicate entries for DRB1*01:01:01:01 have now been removed in the 3.42.0 and Latest branches.
