### ISSUE TITLE
Consistent file and branch naming

### ISSUE THREAD

**Issue by Stikus** [ANHIG/IMGTHLA#240]
Hello, thanks for great work.

We are using your database in our studies and I've written little script for continuous updating when you release new version (any chance to use releases GitHub feature for it btw?).

With 3 last releases I found several inconsistencies:

1. `3.41.2` release still placed on `3410` branch despite having minor version number in branch name - why not `3412` branch or remove it?

1. `3.41.0` release [archive](https://github.com/ANHIG/IMGTHLA/blob/a3b490b6e73aaf6cf8f936f8ef77180bae8fa0e7/Alignments_Rel_3410.zip) contains `Alignments_Rel_3410` folder, `3.41.2` release [archive](https://github.com/ANHIG/IMGTHLA/blob/3410/Alignments_Rel_3412.zip) contains `alignments` folder, `3.42.0` release [archive](https://github.com/ANHIG/IMGTHLA/blob/3420/Alignments_Rel_3420.zip) contains `Alignments_Rel_3420` folder again.

1. Old releases contain `ClassI_nuc.txt` and `ClassI_prot.txt`, `3.42.0` contains `CLASSI_nuc.txt` and `CLASSI_prot.txt`.

And I cannot tell for everyone but for me using Github release archives will be much easier than current archives from branches (especially due to `3.41.0` release archive missing in `3410` branch).

**Comment by jrob119** [comment]
Many thanks for raising this issue, we are constantly looking at how best to report the versioning of the databases releases and in particular for the minor versioning, where we are keen to highlight any important changes to the data. Thanks for suggestion we will take a look.

**Comment by Stikus** [comment]
Thanks for fast answer.
Can you tell me what is correct naming for folders (2) and files (3)? I want to fix my script and report you any issues with this in the future.

**Comment by jrob119** [comment]
For 2 the folder name should be alignments, with the compressed archive using Alignments_Rel_3XXY.zip format, the files it should be cClass and not CLASS.
