### ISSUE TITLE
MICA and MICB are incorrectly named HLA-MICA and HLA-MICB in versions 3.40.0, 3.41.0 and 3.42.0

### ISSUE THREAD

**Issue by mmaiers-nmdp** [ANHIG/IMGTHLA#243]
It looks like a change was made to fix this for 3.39.0 but going forward the hla.xml is using the wrong name for these genes.  The HUGO names are MICA and MICB not HLA-MICA and HLA-MICB.

Recommend fixing the hla.xml files for those three releases and changing this for the future.

**Comment by jrob119** [comment]
Apologies, corrected
