### ISSUE TITLE
404 Error on  https://github.com/ANHIG/IMGTHLA/blob/Latest/xml/hla_ambigs.xsd

### ISSUE THREAD

**Issue by colinhercus** [ANHIG/IMGTHLA#246]
README.md includes

### XML Folder

Please refer to the relevant XSD file for information regarding the XML files, which can be found here: https://github.com/ANHIG/IMGTHLA/blob/Latest/xml/hla_ambigs.xsd

However the link returns a 404

**Comment by jrob119** [comment]
The missing XSD files have been added to the Latest branch.
