### ISSUE TITLE
there is empty fastq after runnign stfr

### ISSUE THREAD

**Issue by jeongmeani** [ANHIG/IMGTHLA#249]
Hi, 

i have some WES data, and using HLA-HD i get HLA-typing result.
but on some data all alleles is "Not typed"

so i run per lines on hlahd.sh.
and i have realized fastq of stfr output is empty.

can i get this reason?

other hla-typing callers(Optitype, Polysolver) work on this data.

Best Regards

Jeongmin

**Comment by jingydz** [comment]
Hi,
I have the same question with you, have you solved it yet？@jeongmean

**Comment by jrob119** [comment]
The original question does not appear to reference files from this repository. If this is for third party applications we are unable to advise.

**Comment by jingydz** [comment]
Ok, thanks. ^~^
