### ISSUE TITLE
Missing MICA/MICB in hla.xml.zip and hla_ciwd.xml.zip in IPD-IMGT/HLA Release 3.43.0

### ISSUE THREAD

**Issue by gschofl** [ANHIG/IMGTHLA#257]
Hi,
maybe this was intentional, but the allele data for MICA and MICB are missing from hla.xml.zip and hla_ciwd.xml.zip in 3.43.0
Moreover the data in hla_ciwd.xml.zip in Latest seem to be still stuck on release 3.42.0

Thanks!

**Comment by jrob119** [comment]
Thanks for raising this, I will look into it,

**Comment by dominicbarkerAN** [comment]
Hi, thanks for bringing this issue to our attention. These corrections have now been made on branch 3.43.0 and Latest.
