### ISSUE TITLE
Discrepancy between nuc/gen and prot alignments for DQB1*02:53Q

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#259]
Since IPD-IMGT/HLA Database release version 3.35.0, the protein alignment for DQB1*02:53Q amino acids 65 and 66 has been discrepant with the nucleotide (and genomic) alignment for codons 65 and 66.

![DQB1-02 53Q_AA65](https://user-images.githubusercontent.com/8935284/108416655-db8e8f00-71e3-11eb-87f2-34974e748bb6.png)
As shown above, in the current release, and since 3.35.0, the sequence of amino acid positions 65 and 66 is "D." indicating a deletion of codon 66; prior to 3.35.0, the sequence was ".D". Note that ".D" is consistent with the sequence of many other DQB1*02 alleles. 

![DQB1-02 53Q_Codon65](https://user-images.githubusercontent.com/8935284/108416663-dd585280-71e3-11eb-8666-e05013c0a8a8.png)
As shown above, in the current release, and prior releases, the sequence of codons 65 and 66 are "...GAC", which should correspond to a ".D" amino acid sequence. This also corresponds with the genomic sequence.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention, this alignment has now been corrected in the Latest, 3440 and all previous branches and will continue to be maintained in future versions.
