### ISSUE TITLE
"/pseudo" tag is missing for exon-5 of DQB1 alleles

### ISSUE THREAD

**Issue by krivonosovak** [ANHIG/IMGTHLA#261]
Hello, 
In 3430 version for a lot of DQB1 alleles "/pseudo" tag was removed from hla.dat, but in previous version it was there.  For example: `DQB1*05:01:01:01`, `DQB1*06:02:01:01`. Is this expected? 

Thanks.

**Comment by jrob119** [comment]
We are currently investigating this

**Comment by dominicbarkerAN** [comment]
The inclusion of a /pseudo tag for non-expressed exon 5 sequences in DQB1 alleles has been reviewed and corrected. These updates are included in 3.43.0, 3.44.0 and the latest branch.

Thank you for bringing this to our  attention
