### ISSUE TITLE
Release for 3.44.0 missing

### ISSUE THREAD

**Issue by Stikus** [ANHIG/IMGTHLA#264]
Hello.
Can you publish release assets for 3.44.0 as you've done for previous releases: https://github.com/ANHIG/IMGTHLA/releases

**Comment by jrob119** [comment]
An archive of the latest files has been added

**Comment by Stikus** [comment]
Thank you, @jrob119 .
Just for your info - `3.44.0` link is `https://github.com/ANHIG/IMGTHLA/releases/tag/3.44.0` but `3.43.0` release link is `https://github.com/ANHIG/IMGTHLA/releases/tag/v3.43.0-alpha` - `v` is missing.
