### ISSUE TITLE
Feedback on "Trialling the use of Git Releases for IPD-IMGT/HLA Releases"

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#270]
There seems to be variation in the structure of the release names of  releases 3.44.0 and 3.44.1.

The name of release 3.44.0, and all the prior releases, is prefixed with a lowercase v, but 3.44.1 does not include the lowercase v prefix in its release name. 

![IPD-IMGT_HLA-GitHub_Releases](https://user-images.githubusercontent.com/8935284/125334730-8f61f980-e300-11eb-93b0-d7704787dd04.png)

This results in inconsistency in the URLs for successive releases:

https://github.com/ANHIG/IMGTHLA/tree/3.44.1-alpha
https://github.com/ANHIG/IMGTHLA/tree/v3.44.0-alpha
https://github.com/ANHIG/IMGTHLA/tree/v3.43.0-alpha
https://github.com/ANHIG/IMGTHLA/tree/v3.42.0-alpha
https://github.com/ANHIG/IMGTHLA/tree/v3.41.2-alpha
https://github.com/ANHIG/IMGTHLA/tree/v3.02.0.1.0-alpha (for release v3.41.0)

Ideally, all release names would use the identical release-name structure, which would facilitate easy, automated access to them. 

The inclusion of the v also distinguishes the URLs of the releases from the URLs of the branches:

https://github.com/ANHIG/IMGTHLA/tree/3440
https://github.com/ANHIG/IMGTHLA/tree/3430
https://github.com/ANHIG/IMGTHLA/tree/3420
https://github.com/ANHIG/IMGTHLA/tree/3410

It isn't clear if that is intentional or not, but consistent use of the v for releases would make it easy to distinguish the two going forward.

**Comment by serge2016** [comment]
+1

**Comment by bmschoene** [comment]
+1

**Comment by jrob119** [comment]
Updated 3.44.1 and also the historical releases 3.0.0 to 3.3.0
