### ISSUE TITLE
Unable to download hla.xml.zip for 3.45.0

### ISSUE THREAD

**Issue by mgeorge-nmdp** [ANHIG/IMGTHLA#272]
https://github.com/ANHIG/IMGTHLA/blob/Latest/xml/hla.xml.zip

reports that it is not a valid zip file.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention. Another copy of this compressed file has been uploaded and tested on branches 3450 and Latest. I apologise for the inconvenience.
