### ISSUE TITLE
C*04:82 and A*24:155N cannot be typed

### ISSUE THREAD

**Issue by yuli19900926** [ANHIG/IMGTHLA#277]
we have a sample the Sanger result is C*04:82, but the HLA-HD result is C*04:01:01 or C*04:339:01; and we also have another sample the Sanger result is A*24:155N, but the HLA-HD result is A*24:02:01; What they have in common is an insertion or deletion on the exon.

**Comment by jrob119** [comment]
This repo is for the data from the IPD-IMGT/HLA Database, and as such we cannot provide support for third party software which utilises HLA data like HLA-HD. If you require support for HLA-HD please contact the developers directly.
