### ISSUE TITLE
cDNA vs CDS

### ISSUE THREAD

**Issue by joycekang** [ANHIG/IMGTHLA#284]
Hi! Thanks for this great resource. The readme says that the .nuc files are for the CDS (coding sequence, so I assume only exons), however when I inspect the .nuc files they say they are “cDNA” sequences which I assume include introns as well. Do you know if they are truly CDS or cDNA? Thanks!

**Comment by jrob119** [comment]
The sequences in the. nuc files are the available exons only. There will be no intronic sequence included, unless there is a splice site mutation that means some of the intronic sequence is now considered part of the exon.

**Comment by joycekang** [comment]
Got it. thank you!

**Comment by joycekang** [comment]
Based on above, it seems like the "nuc" sequences are CDS (of the available exons). As a follow up question, it seems like on the IMGT/HLA website they say the "nuc" sequences are cDNAs, which is confusing: https://www.ebi.ac.uk/ipd/imgt/hla/nomenclature/alignments.html Are the sequences the same between these two data sources? Thanks!

**Comment by jrob119** [comment]
Within the database the terms cDNA, CDS and nuc refer to the same sequences, these will be exon only and not contain any intron.
