### ISSUE TITLE
Renaming of allele MICA*007:02

### ISSUE THREAD

**Issue by bmschoene** [ANHIG/IMGTHLA#285]
Hi,

according to the allele search tool (https://www.ebi.ac.uk/ipd/imgt/hla/allele.html) and the hla.dat file, the allele MICA\*007:02 has been extended and renamed to MICA\*111:01:01 in March 2020.

However, according to both sources, there currently is no allele named MICA*111:01:01 in the database. There _is_ a MICA\*111:01, though. Is this the allele that was originally 007:02? 

The file Deleted_alleles.txt contains the same information as hla.dat, while hla_nom.txt seems to imply MICA\*111:01 as the correct new name: 
"MICA*;007:02;20001214;20200331;**111:01**;Sequence renamed"

Can you please look into this and make it consistent?

Thank you!

**Comment by jrob119** [comment]
Thank you for highlighting this, we will look at updating the necessary files to ensure consistency in naming of the allele in question.

**Comment by jrob119** [comment]
Issue addressed in the latest update.
