### ISSUE TITLE
Missing Sequence renamed date for B*07:02:06 and DQB1*02:01:10

### ISSUE THREAD

**Issue by saulievue** [ANHIG/IMGTHLA#287]
Missing Sequence renamed date for B*07:02:06 and DQB1*02:01:10 in the Deleted_alleles.txt for DB 3.46.0.

B*07:02:06 - 2021-07-30
DQB1*02:01:10 - 2021-07-30

Missing in the deleted text file, but present in the hla_nom text file 07/30/2021.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention, this has now been updated on the 3460 and Latest branch.
