### ISSUE TITLE
CDS sequences in hla.dat and *_nuc.txt don't match

### ISSUE THREAD

**Issue by krivonosovak** [ANHIG/IMGTHLA#290]
Hello, 

For some alleles, allele sequence from the hla.dat file does not match sequence from the alignment files:
* C\*03:23N: exon-3 is shotter in hla.dat than in alignments/C_nuc.txt. 
```
hla.dat      ................................................................GTATGACCAGTACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGATCTGCGCTCCTGGACCGCCGCGGACACGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCCTGTGCGTGGAGTGGCTCCGCAGATACCTGAAGAATGGGAAGGAGACGCTGCAGCGCGCGG
C_nuc.txt    GGTCTCACATCATCCAGAGGATGTATGGCTGCGACGTGGGGCCCGACGGGCGCCTCCTCCGCAGGTATGACCAGTACGCCTACGACGGCAAGGATTACATCGCCCTGAACGAGGATCTGCGCTCCTGGACCGCCGCGGACACGGCGGCTCAGATCACCCAGCGCAAGTGGGAGGCGGCCCGTGAGGCGGAGCAGCTGAGAGCCTACCTGGAGGGCCTGTGCGTGGAGTGGCTCCGCAGATACCTGAAGAATGGGAAGGAGACGCTGCAGCGCGCGG
```
* exon-7 is 2 bases shorter in alignments/E_nuc.txt than in hla.dat for all alleles
```
Example for allele E*01:01:01:01:
hla.dat      GGAGCGACAGTGCCCAGGGGTCTGAGTCTCACAGCTTGTAAAG
E_nuc.txt    GGAGCGACAGTGCCCAGGGGTCTGAGTCTCACAGCTTGTAA..
```
* DRB4\*01:03:01:02N, DRB4\*01:03:01:13N, DRB4\*01:14N: exon-2 is 17 bases shorter in hla.dat than in alignments/DRB_nuc.txt 
```
Example for allele DRB4*01:03:01:02N:
hla.dat      .................GCTAAGTGTGAGTGTCATTTCCTCAATGGGACGGAGCGAGTGTGGAACCTGATCAGATACATCTATAACCAAGAGGAGTACGCGCGCTACAACAGTGACCTGGGGGAGTACCAGGCGGTGACGGAGCTGGGGCGGCCTGACGCTGAGTACTGGAACAGCCAGAAGGACCTCCTGGAGCGGAGGCGGGCCGAGGTGGACACCTACTGCAGATACAACTACGGGGTTGTGGAGAGCTTCACAGTGCAGCGGCGAG
E_nuc.txt    CACGTTTCTTGGAGCAGGCTAAGTGTGAGTGTCATTTCCTCAATGGGACGGAGCGAGTGTGGAACCTGATCAGATACATCTATAACCAAGAGGAGTACGCGCGCTACAACAGTGACCTGGGGGAGTACCAGGCGGTGACGGAGCTGGGGCGGCCTGACGCTGAGTACTGGAACAGCCAGAAGGACCTCCTGGAGCGGAGGCGGGCCGAGGTGGACACCTACTGCAGATACAACTACGGGGTTGTGGAGAGCTTCACAGTGCAGCGGCGAG
```
* DQB1\*05:283N:  exon-6 is shotter in alignments/DQB1_nuc.txt than in hla.dat
```
hla.dat         GGCTTCTGCACTGACTCCTGA
DQB1_nuc.txt    GGCTTCTGCACTGA.......
```
* DPA1*02:38Q:  exon-4 is shotter in alignments/DQB1_nuc.txt than in hla.dat
```
hla.dat        AGGCCCAAGAGCCAATCCAGATGCCTGAGACAACGGAGACTGTGCTCTGTGCCCTGGGCCTGGTGCTGGGCCTAGTGGGCATCATCGTGGGCACCGTCCTCATCATAAAGTCTCTGCGTTCTGGCCATGACCCCCGGGCCCAGGCCCCTGTGAAATACTGTAAAGGTGGGAATGTAAAAAAGGAGGTCCTAGAATTTGTAGAATGTAAGGAAGGGAGGAAAAATTCAATCTGA
DPA1_nuc.txt   AGGCCCAAGAGCCAATCCAGATGCCTGAGACAACGGAGACTGTGCTCTGTGCCCTGGGCCTGGTGCTGGGCCTAGTGGGCATCATCGTGGGCACCGTCCTCATCATAAAGTCTCTGCGTTCTGGCCATGACCCCCGGGCCCAGGCCCCTGTGA................................................................................
```
Is this expected?

Thanks.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this to our attention, we are looking into resolving this issue

**Comment by jrob119** [comment]
This should be resolved in the latest release and we are looking at updating the previous files.

**Comment by dominicbarkerAN** [comment]
Thank you for your patience in waiting for this issue to be resolved. The sequences in the text alignments are now correct and should match the hla.dat in the C_nuc.txt, DQB1_nuc.txt and DPA1_nuc.txt. 

The sequence marked up in the hla.dat and E_nuc.txt files are both correct. HLA-E has a stop codon in exon 7 two bases before the end of the exon. These two bases are not included in files representing the coding sequence.  You can see this difference in the hla.dat file by looking at the last feature in the CDS line and exon 7 in the individual features:

```
FT   CDS             join(301..364,495..764,1009..1284,1906..2181,2306..2422,
FT                   3173..3205,3310..3350)
...
FT   exon            3310..3352
FT                   /number="7"
```

The sequence extracted using the CDS coordinates matches to the sequence in the E_nuc.txt files.
