### ISSUE TITLE
missing alleles

### ISSUE THREAD

**Issue by jessicaedwards82** [ANHIG/IMGTHLA#293]
the alleles listed in the 3.47.0 version report for at least A and B are missing from the fasta files.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention. Could you please specify what files and what branch you are accessing and not finding the new alleles present as we have not currently been able to replicate your issue.

**Comment by dominicbarkerAN** [comment]
Without further information we have not been able to replicate this issue and consider this now closed. If you are able to provide with further information in future please comments on and re-open this issue.
