### ISSUE TITLE
Groups missing from hla_nom_p.txt and hla.xml.zip IPD-IMGT/HLA Release 3.47.0

### ISSUE THREAD

**Issue by saulievue** [ANHIG/IMGTHLA#295]
Hi,

There are some issues that we want to bring to your attention:

1.) Can you please add the P group, DPA1*03:05P, to the hla_nom_p.txt file?

2.) Can you please add the P group, DRB3*02:171P, to the hla_nom_p.txt file?

3.) Can you please add the P group, DRB3*03:22P, to the hla.xml.zip file? 

Thank you,
Saulie Vue

**Comment by dominicbarkerAN** [comment]
Dear Saulie Vue,

Thank you for bringing this issue to our attention. We have reviewed these issues and made the following updates:

1) DPA1*03:05P has been changed to DPA1*03:01P in DPA1*03:05:01:01Q and DPA1*03:05:01:02Q in hla.xml.
2) DRB3*02:171P has been changed to DRB3*03:22P in DRB3*02:171, DRB3*02:173:01 and DRB3*02:173:02 in hla.xml.
3) Issue corrected by above.

In each case the P group designation in the hla_nom_p.txt file was found to be correct and updates made to the hla.xml file.

These updates are available on 3470 and the Latest branch.

Thank you again for bringing this issue to our attention.
