### ISSUE TITLE
3.47.0 New alleles say "Sequence unchanged" instead of "New Allele" for release status in hla.xml.zip file

### ISSUE THREAD

**Issue by saulievue** [ANHIG/IMGTHLA#297]
Hi all,

The new alleles introduced in 3.47.0 has "Sequence unchanged" instead of "New allele" for release status in the hla.xml.zip file file. In previous DB releases, new alleles was assigned "New allele" as the release status. Could you please review if this was an error in the hla.xml.zip file or if it was intentional? I attached an example of a new allele from DB 3.27.0 with release status "New allele". Thank you for your help.

Kind Regards,
Saulie

![image-2022-02-15-13-58-51-651](https://user-images.githubusercontent.com/52675474/154135577-4f83dca6-c636-48eb-9a62-f7a5742127ef.png)

**Comment by dominicbarkerAN** [comment]
Hi Saulie,

We have confirmed this issue in the latest version of the hla.xml file and will be providing a patch of this shortly. Thank you again for bringing this issue to our attention.

**Comment by saulievue** [comment]
Hi Dominic,

Please keep me posted once completed. Thank you again for your help.

**Comment by saulievue** [comment]
Hi all,

Are you able to provide a status update on the issue with the hla.xml file? Has the file been corrected?

**Comment by dominicbarkerAN** [comment]
Hi Saulie,

I apologise for the delay. Due to recurring issues with this file we have been carrying out a comprehensive review of it's contents. This has unfortunately taken more time that we anticipated however we expect a fully corrected version of this file to be available in the coming days. Thank you for your patience.

**Comment by dominicbarkerAN** [comment]
Dear Saulie,

Thank you again for your patience. We have finished building a new version of the hla.xml file which has included a comprehensive patch to much of the meta data though the sequences remain correct and unchanged. This updated has included an update for the releasestatus field in line with the release version report and is available on the 3470 and Latest branches.
