### ISSUE TITLE
DRB4*01:03:01:02N intron 1 - exon 2 annotation

### ISSUE THREAD

**Issue by futak** [ANHIG/IMGTHLA#298]
Dear All,

In older hla.dat versions the intron 1 exon 2 border seems to be in a different position for HLA-DRB4*01:03:01:02N compared to newer versions (including 3.45.1, 3.46.0, 3.47.0) while the allele sequence itself seems to be identical.

Example for the old annotation (IMGT/HLA 3.42.0):
> FT       intron          414..9984
FT                          /number="1"
FT          exon           9985..10254
FT                          /number="2"

Example for the new annotation (IMGT/HLA 3.47.0):
>FT      intron          414..10001
FT                           /number="1"
FT        exon           10002..10254
FT                          /number="2"

This may be related to issue #290.

Can you please provide some guidance about this change and clarify which version is correct?

Thanks,

**Comment by dominicbarkerAN** [comment]
Dear Futak,

Thank you for your query. DRB4*01:03:01:02N is a splice site variant where the start of exon 2 occurs 17bp later than in the reference. Historically this has been marked up inconsistently in different file formats but has now been normalized across all files. The sequence extracted using the CDS line

> FT   CDS             join(314..413,10002..10254,12984..13265,13970..14080,
> FT                   14555..14578,14881..14894)

Is the correct CDS sequence after the impact of abberant splice sites have been taken into account.

As such the latest version is correct.

**Comment by futak** [comment]
Dear dominicbarkerAN,

Thank you for the clarification!
