### ISSUE TITLE
There are no HLA-H alleles in XML

### ISSUE THREAD

**Issue by virtualparadox** [ANHIG/IMGTHLA#301]
Hello! 

There are no HLA-H alleles in the XML (3.47). I found the missing alleles in hla.dat. 

Cheers.

**Comment by jrob119** [comment]
At the current time the XML format only contain certain genes, we are looking to expand this to cover all the genes included in the hla.dat file. The XML format was originally designed to only include HLA-A, -B, -C, -DRB1, -DQB1 and DPB1 and we have been working to expand it to include more of the genes in the database.
