### ISSUE TITLE
Allelelist_history.txt not updated to 3.48.0

### ISSUE THREAD

**Issue by mmelchers** [ANHIG/IMGTHLA#304]
I noticed though that a couple of days ago you released version 3.48.0 of the nomenclature. The “Allelelist_history.txt” file does not seem to have been updated though. Was that intentional? Maybe there was some work that needed to be done on it before you wanted to release it. I just wanted to make you aware.

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention. Unfortunately this file was not uploaded upon the original release due to an oversight. This issue has now been corrected and teh Allelelist_history.txt file is available from the 3480 and Latest branches.
