### ISSUE TITLE
Novel HLA alleles

### ISSUE THREAD

**Issue by freedomq8** [ANHIG/IMGTHLA#306]
Hi there, 

I appreciate your work on HLA-HD tool. I recently used it for project and I need some clarification for below points. 
1) is there a symbol denoted for novel alleles ? or to put it in another way how it deasl with unknown/novel alleles ?
2) how the IMGT/HLA Database being used exactly in HLA-HD tool (to write it in my methods and material part)
The database is a repository of reference sequences and HLA-HD is used for typing alleles so HLA-HD type against specific version of the IPD-IMGT/HLA Reference Database? 

Thanks

**Comment by dominicbarkerAN** [comment]
Hello,

The HLA-HD tool is a piece of 3rd party software and we are not a part of it's development or maintenance. For questions regarding their software please get in touch with them directly.
