### ISSUE TITLE
3.49.0 alignments DRB_nuc.txt file issue

### ISSUE THREAD

**Issue by saulievue** [ANHIG/IMGTHLA#309]
Hi,

We are encountering a couple of errors when trying to process the alignment DRB_nuc.txt file. It's due to the the lines in the data file. Our processing script is considering the '-' as part of the allele as shown in the error. Could you please add a space after the N expression for the two alleles below?

Actual (no spaces after N):
DRB1*15:200:01:01N-
DRB1*15:200:01:02N-

Expected (add space after N):
DRB1*15:200:01:01N -
DRB1*15:200:01:02N -

Thanks,
Saulie

**Comment by dominicbarkerAN** [comment]
Hi,

Thank you for bringing this issue to our attention. This issue has now been corrected in the latest commit of the 3490 and Latest branch.
