### ISSUE TITLE
hla.p.json

### ISSUE THREAD

**Issue by drkoryjohns** [ANHIG/IMGTHLA#311]
Hello,

I am trying to run arcasHLA using the test commands provided on the git page but incur error:

traceback (most recent call last):
  File "/arcasHLA/scripts/genotype.py", line 707, in <module>
    with open(hla_json, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/arcasHLA/scripts/../dat/ref/hla.p.json'

When I inspect the reference.py script, it appears there is this line that is commented out:

https://github.com/RabadanLab/arcasHLA/blob/master/scripts/reference.py#L458

Is that the issue, should this line be uncommented or how can I circumvent the error?

Thank you,

Kory Johnson

**Comment by jrob119** [comment]
This issue has been posted to the IMGTHLA repo not the arcasHLA repo, please raise this issue with the ArcasHLA developers, as it appears to refer to their code base, not the reference files.
