### ISSUE TITLE
Duplication of 'Human MHC;' in hla.dat

### ISSUE THREAD

**Issue by jlimauro** [ANHIG/IMGTHLA#313]
I noticed that after 3.47 there are over 8000 lines with duplication of _Human MHC;_ varying from two to four occurrences on the KW line of multiple alleles. I use a utility that verifies this file and I'm not sure if I am expected now to see possible duplications of _Human MHC;_ on the KW lines or not? I see these duplications in both the 3.48 and 3.49 versions of the hla.dat file. Before 3.48 this was not the case.

What I see in hla.dat files after 3.47:
`KW   Human MHC; Human MHC; Human MHC; HLA; Class I; HLA-B; Allele; HLA-B*07:02:01:01;`

What I was expecting in hla.dat file:
`KW   Human MHC; HLA; Class I; HLA-B; Allele; HLA-B*07:02:01:01;`

**Comment by dominicbarkerAN** [comment]
Hi, thank you for bringing this issue to our atteion. This has now been corrected and the hla.dat file has been updated on the 3480, 3490 and Latest branch.
