### ISSUE TITLE
DRB1 nuc

### ISSUE THREAD

**Issue by AlsoATraveler** [ANHIG/IMGTHLA#319]
Hi, can you provide the DRB1_nuc.txt file?

**Comment by dominicbarkerAN** [comment]
Hi, currently we do not build individual DRB1_nuc.txt file however these alleles can be viewed in the DRB_nuc.txt file. We are aware that there is interest from our users in including a number of additional files and we are currently reviewing the files we provide to see what additional files we believe would be useful and appropriate.

I will provide an update when we have completed this review.

**Comment by AlsoATraveler** [comment]
> Hi, currently we do not build individual DRB1_nuc.txt file however these alleles can be viewed in the DRB_nuc.txt file. We are aware that there is interest from our users in including a number of additional files and we are currently reviewing the files we provide to see what additional files we believe would be useful and appropriate.
> 
> I will provide an update when we have completed this review.

thanks

**Comment by dominicbarkerAN** [comment]
Following interest from several users we have now included DRB1, DRB3, DRB4 and DRB5 nuc.txt files in the 3.51.0 version of the database.

**Comment by AlsoATraveler** [comment]
> Following interest from several users we have now included DRB1, DRB3, DRB4 and DRB5 nuc.txt files in the 3.51.0 version of the database.

This is great news, thank you.
