### ISSUE TITLE
HGVS

### ISSUE THREAD

**Issue by obedaram** [ANHIG/IMGTHLA#320]
On the IPD-IMGT/HLA website, I'm able to click and access the HGVS report for specific alleles. Are these accessible through one of the documents on the GitHub?

**Comment by dominicbarkerAN** [comment]
Hi Obed Garcia,

Thank you for your suggestion, we are always interested to know new features our users would like to see. Currently there is no file containing the HGVS data for download through the git repository. We are aware that support for this format is desirable to some of our users and are investigating the best possible solutions to providing that support.
