### ISSUE TITLE
The date field is not populated in the Allelelist_history.txt file in release version 3.50.0

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#322]
Not much more to say than what is in the title. 

Here is a screenshot. 

<img width="1015" alt="Allelelist_history_3 50 0_missing-date" src="https://user-images.githubusercontent.com/8935284/206562685-ae899d6e-cdb0-4212-81b5-3960f4e9bcbb.png">

**Comment by dominicbarkerAN** [comment]
Hello,

Thank you for bringing this issue to our attention. This has now been corrected in the latest commit of the 3500 and Latest branch.
