### ISSUE TITLE
There is no DRB5_nuc.txt

### ISSUE THREAD

**Issue by suppakoko** [ANHIG/IMGTHLA#324]
Hi recently I am search novel HLA genoype. kourami is good tool.
But, while formating updated alignments file of v3.50.0
updating is failed with this error messange below

>>>>>>>>>  Processing   [DRB5]  <<<<<<<<<<
nucRefAl:       DRB1*01:01:01:01        genRefAl:       DRB5*01:01:01
        refGeneName on nuc and gen are NOT same
Reference sequence entry [DRB5*01:01:01] is NOT found in nuc alignments.
Check the alignment files.

I also tried to update with v3.49.0, but same error result.

Could help me?

**Comment by dominicbarkerAN** [comment]
Hello, historically the DRB1-9 nucleotide sequences have been included in a single DRB_nuc.txt file. However we have had interest from multiple users about also having DRB1_nuc.txt, DRB3_nuc.txt, DRB4_nuc.txt and DRB5_nuc.txt files and these are now included in the 3.51.0 release of the database.

As we do not develop or maintain Kourami we cannot comment on issues with their software.

**Comment by sjmack** [comment]
Will the DRB_nuc.txt and DRB_prot.txt files continue to be generated/supported, or is there a plan for those files to be eliminated in a future IPD-IMGT/HLA Database release? If so, how will the nucleotide sequences for DRB6/7/8/9 be made available?

**Comment by dominicbarkerAN** [comment]
The DRB_nuc.txt and DRB_prot.txt files will continue to be built and supported for the foreseeable future.
