### ISSUE TITLE
A*02:506N

### ISSUE THREAD

**Issue by AlsoATraveler** [ANHIG/IMGTHLA#328]
Hello, in version 3.40, why is there no sequence of A*02:506N in A_gen.fasta?

**Comment by AlsoATraveler** [comment]
Can the sequence of the intron at the corresponding position in A*01:01:01:01 be added at both ends according to the position of the exon? I need sequences at both ends for data simulation.

A*01:285N is also the same as A*02:506N in version 3.40.

**Comment by jrob119** [comment]
The database represent the reference sequences for HLA alleles and only includes sequence that has been confirmed and submitted. We do not impute sequence to fill gaps or match sequence lengths. If you wish to pad sequences, you will need to determine your own local rules for this.
