### ISSUE TITLE
About SNP position

### ISSUE THREAD

**Issue by AlsoATraveler** [ANHIG/IMGTHLA#329]
I found that in the msf files of the multiple sequence alignment results obtained by using different alignment software, there are differences in the positions of SNPs or indels of the same type under the same exon. How do you ensure that the msf files you provide are accurate? Where can I check the logic or code of the comparison software you use? Looking forward to your answer, thank you.

**Comment by jrob119** [comment]
Thanks for your enquiry, the alignments and subsequent positioning of SNPs an indels will be dependant on the software used, the scoring matrix and the sequences aligned, in particular the inclusion of sequences which cause indels. It can therefore be difficult to replicate alignments particularly with such a variable system as HLA and the numbers of sequences required for each alignment. Sequence alignments are an artificial representation of how two sequences align and are there to allow human understanding of the difference and as such can be subjective and open to interpretation. MSF files are produced based on validated sequence alignments built using published software.
