### ISSUE TITLE
About alignment result

### ISSUE THREAD

**Issue by AlsoATraveler** [ANHIG/IMGTHLA#331]
Hello, in \*_nuc.txt under the alignment folder, each gene has a type with the base ATCG, what is the basis for the selection of this type? Is it used as a reference comparison? For example, A\*01:01:01:01 of the A gene. Will I get different results if I change the type (except for the different representations on the type sequence)?

My understanding is that during multiple sequence alignment, if you select a complete sequence (that is, no missing sequence for each exon and intron) to display ATCG, and use "-" or other characters instead, it will not affect the multiple sequence alignment results. Is this understanding correct?

**Comment by jrob119** [comment]
Please see our online documentation, both the README.md file for this repository;

https://github.com/ANHIG/IMGTHLA#readme

As well as https://www.ebi.ac.uk/ipd/imgt/hla/alignment/help/ which helps explains the files we produce and conventions used.
