### ISSUE TITLE
DRB3*03:57Q-related issue in the DRB_prot.txt file for releases 3.49.0 to 3.51.0

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#332]
The nine nucleotide insertion in DRB3*03:57Q results confusing position numbering in the DRB_prot.txt file. The three residue insertion in this protein results in an indel position in the alignment being identified as position 67, when the position to the immediate right is the actual position 67. This makes it difficult to identify the proper position coordinates for that section of the alignment. I notice a similar issue for the HLA-A and HLA-B protein alignments. The ideal solution would be to start the numbering of positions after any initial indel (".") positions.

<img width="1040" alt="DRB_position_67_confusion" src="https://user-images.githubusercontent.com/8935284/227759483-22b190ba-ce90-42df-937a-76ac186e5c2a.png">

<img width="1043" alt="HLA-A_position_155_confusion" src="https://user-images.githubusercontent.com/8935284/227759486-aafb3290-6672-48d9-ac33-33df5a569430.png">

<img width="1024" alt="HLA-B_position_141_confusion" src="https://user-images.githubusercontent.com/8935284/227759496-a08e8d50-0be9-47aa-ba28-8937631d5356.png">

**Comment by jrob119** [comment]
Thanks for the feedback on this, with regards to numbering this is based on only valid bases in the reference sequence, and as such the '.' is not counted as a valid base and the numbering would resume start once the first valid base is encountered.
