### ISSUE TITLE
Invalid allele name "5N" instead of "50N" IPD-IMGT/HLA Release 3.52.0

### ISSUE THREAD

**Issue by saulievue** [ANHIG/IMGTHLA#336]
Hi,

We found an issue with in the Deleted_alleles.txt file. Invalid allele name "5N" instead of "50N". Please investigate. 

HLA30032,C*03:03:01:50,Sequence renamed C*03:03:01:5N (July 2021)

https://github.com/ANHIG/IMGTHLA/blob/Latest/Deleted_alleles.txt#L226

Thanks,
Saulie

**Comment by dominicbarkerAN** [comment]
Hi Saulie,

Sorry for not responding to this issue sooner, thank you for bringing this issue to our attention. This has been corrected in 3.52.0, 3.53.0 and the Latest branch.
