### ISSUE TITLE
What does the pipe character "|" indicate in the nuc.txt and gen.txt files?

### ISSUE THREAD

**Issue by slowkow** [ANHIG/IMGTHLA#338]
![Screenshot 2023-06-14 at 3 30 00 PM](https://github.com/ANHIG/IMGTHLA/assets/209714/9e236c51-8c7a-4562-83e9-8a418842a6b7)

I downloaded the file [`DRB1_nuc.txt`](https://github.com/ANHIG/IMGTHLA/blob/Latest/alignments/DRB1_nuc.txt) from the latest release 3.52.0

In the screenshot above, please note:

- Line 9 says "AA codon -29"
- Line 3529 says "AA codon -4"

**Comment by jrob119** [comment]
The pipe represents the exon/exon border, and the negative codons are because the amino acid numbering uses the first base of the mature protein as 1. Please see;

https://www.ebi.ac.uk/ipd/imgt/hla/alignment/help/

**Comment by slowkow** [comment]
Thanks for your quick reply!

I read the documentation, but I didn't see any mention of "exon border" or the pipe character "|". Sorry if I missed something, I could always be mistaken.

(By the way, it was my mistake to mention the negative codons. This is already explained in the documentation, but I pressed the <kbd>Comment</kbd> button too early, before I finished writing my question. Sorry!)

I want to ask a follow up question about the exon/exon border, to make sure that I am interpreting this correctly.

If I am understanding you correctly, we see 6 exons below, right? Each exon is separated from the other exons by the `|` character?

![DRB1_01-01-01-01_nuc](https://github.com/ANHIG/IMGTHLA/assets/209714/239f8df2-da71-403f-bb2a-b6cc29e15aad)

I used Photoshop to color the screenshot and make it easier to see each distinct exon.

My current understanding is that:
- `DRB1_nuc.txt` has only the exonic sequences, and the `|` character indicates the exon/exon border.
- `DRB1_gen.txt` has both the intronic and exonic sequences, and the `|` character indicates the intron/exon border and the exon/intron border.

**Comment by slowkow** [comment]
While I am still looking at these files, I thought I would mention one observation.

The number of alleles in the `gen` file is 597, but the number in `nuc` and `prot` is 3516:

```
grep DRB1 DRB1_gen.txt | cut -f2 -d' ' | grep DRB1 | sort -u | wc -l
     597

grep DRB1 DRB1_nuc.txt | cut -f2 -d' ' | grep DRB1 | sort -u | wc -l
    3516

grep DRB1 DRB1_prot.txt | cut -f2 -d' ' | grep DRB1 | sort -u | wc -l
    3516
```

After reading the documentation, I couldn't tell if this is expected or not.

**Comment by jrob119** [comment]
Taken from our FAQ page;

Why are there more HLA Alleles in the hla_nuc.fasta than the hla_gen.fasta?

The difference between alleles included in the hla_nuc.fasta and hla_gen.fasta files is that we do not have complete sequence for all alleles. In order for an allele to be included in the hla_gen.fasta file we require a single contigous sequence from the start codon to the stop codon including all intervening exons and introns.

**Comment by slowkow** [comment]
Thanks! For other people finding this discussion thread, here is the link to the FAQ page: https://www.ebi.ac.uk/ipd/imgt/hla/about/help/faq/
