### ISSUE TITLE
New and changed attributes: releasestatus and releasecomments

### ISSUE THREAD

**Issue by mallen2** [ANHIG/IMGTHLA#340]
Good morning, 

We noticed that in the 3.53 hla.xml file an attribute has changed and another has been added: releasestatus and releasecomments

Can you explain or point me to documentation that explains what releasestatus and releasecomments mean? 

Thank you!
Marney

**Comment by dominicbarkerAN** [comment]
Hello Marney,

I apologise for this change not being better documented upon release. In brief the releasestatus attribute now contains a binary flag of "Deleted" or "Public" to allow for ease of filtering. The releasecomments attribute contains information about change to an allele in the relevant release, this contains the information which was previously stored in the releasestatus attribute.

A note has been added to the xml section of the README.

I apologise for any inconvenience caused.

**Comment by mallen2** [comment]
Thank you Dominic.

Marney Milsten
Product Owner, Genomic Services
500 N 5th St, Minneapolis, MN 55401-1206.
Phone: (763) 406-8305 Email: ***@***.***

***@***.***
***@***.***
Be the one to save a life. Be The Match. Join now<http://marrow.org/JOIN/Join_Now/join_now.html>.
