### ISSUE TITLE
TCE group assignment for DPB1* 1148:01Q and 1038:01Q

### ISSUE THREAD

**Issue by zabeen** [ANHIG/IMGTHLA#344]
In v3.53.0, TCE group assignment for DPB1* 1148:01Q and 1038:01Q is now `1` when it was previously "" (i.e., no assignment).

Other alleles in the same G groups, 04:01:01G and 01:01:01G, map to TCE group `3`.

This has an impact on search algorithms that use the TCE group file, [as described here](https://github.com/Anthony-Nolan/Atlas/issues/1028), because now the G groups don't have a single TCE group assignment leading to an "Unknown/Ambiguous" DPB1 match grade.

The fix has been to manually amend the assignments of the DPB1 alleles to `3` but this is not a long term solution as it will be overwritten if the latest IMGT/HLA release retains the `1` mapping.

**Comment by jrob119** [comment]
We are aware of the issue and actively investigating

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention, we have investigated and provided a patch in the latest commit  [a549c5b](https://github.com/ANHIG/IMGTHLA/commit/a549c5b255da7d988a70cf7f7a2bdb5b1ae5b00a). Please see commit comment for details.

**Comment by zabeen** [comment]
Many thanks for the fix! However, as the new commit involves several data changes, should the minor version number be incremented to v3.53.1? Or is this only done for changes to the allele list?

**Comment by jrob119** [comment]
As per the README, the final digit is reserved for sequence changes between releases, changes like this are logged using commit number
