### ISSUE TITLE
Alignments missing most of sequence

### ISSUE THREAD

**Issue by nwheatleKite** [ANHIG/IMGTHLA#346]
When looking at alignments/A_prot.txt, most of the sequence is not available. Only the N and C terminus. Why is this? Is it an error? How do I get the full alignments?

**Comment by dominicbarkerAN** [comment]
Could you provide more information on the issue you are seeing, such as git branch. Having reviewed the A_prot.txt file on the Latest branch of the repository I am unable to find the issue you are describing and can see the complete HLA-A protein sequence included in the alignment.

**Comment by dominicbarkerAN** [comment]
As we have not had further information on this issue we cannot look into this further. If you are able to give more information we will re-open this issue.
