### ISSUE TITLE
The DPA2 and DPB2 nucleotide alignments include codon numbering but have no cognate peptide alignments

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#347]
Unlike the nucleotide alignments for the HLA-H, -J, -K, -L, -N, -S, -T, -U, -V, -W and -Y pseudogenes and gene fragments, which do not have protein alignments, the nucleotide alignments for -DPA2 and -DPB2 include an "AA codon" subheader, with codon numbers, but have no corresponding protein alignments (because they are pseudogenes). 

Is this intentional, or an oversight? It is confusing. 

<img width="1106" alt="Screen Shot 2023-09-15 at 12 16 20 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/3301dc9b-6606-4ee4-93f8-a2ecd0b3402d">
<img width="1162" alt="Screen Shot 2023-09-15 at 12 17 45 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/0cfb4c3b-79a3-47ec-aab5-ef174a6cc30b">
<img width="1190" alt="Screen Shot 2023-09-15 at 12 18 33 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/a22e1537-10ee-42d8-a051-1ae3879a16f4">
<img width="1353" alt="Screen Shot 2023-09-15 at 12 18 11 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/a99b1695-b309-46d0-8229-d37221b1efe8">

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this issue to our attention. We agree that pseudogenes should not include codon numbering position in the nuc.tst files and we will be updating these files in the upcoming release.

**Comment by dominicbarkerAN** [comment]
This issue has now be resolved in the 3.54.0 release
