### ISSUE TITLE
3.54.0 release tag

### ISSUE THREAD

**Issue by qidi-yang** [ANHIG/IMGTHLA#351]
Could you add 3.54.0 to the list of releases, please? Thanks!

**Comment by serge2016** [comment]
Same here. Add it, please!

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this issue to our attention, this release tag has now been made.

**Comment by Stikus** [comment]
@dominicbarkerAN tag was named incorrectly:
![image](https://github.com/ANHIG/IMGTHLA/assets/41360525/d8c16f10-ba37-4dc6-8b20-034775dc26fa)


[v.354.0-alpha](https://github.com/ANHIG/IMGTHLA/tree/v.354.0-alpha) instead of `v3.54.0-alpha` as before. Can you fix it?

**Comment by dominicbarkerAN** [comment]
@Stikus Thank you for bringing this issue to our attention. this has now been updated.

**Comment by serge2016** [comment]
Dear @dominicbarkerAN, fix (remove) one more dot, please:
![image](https://github.com/ANHIG/IMGTHLA/assets/18323865/83c090bb-bb35-4464-94fb-631e45b380d4)

**Comment by serge2016** [comment]
Dear @dominicbarkerAN, remove the extra dot again, please..
![image](https://github.com/ANHIG/IMGTHLA/assets/18323865/d98c80e3-cc80-4da4-b174-952c6826f0d5)

**Comment by dominicbarkerAN** [comment]
I have corrected the release tag for 3.55.0 and 3.54.0 and removed all tags with incorrect formatting. Thank you for your patience.

**Comment by serge2016** [comment]
Thank you! Now looks normal! Great!
![image](https://github.com/ANHIG/IMGTHLA/assets/18323865/23508a2f-6dbb-47a4-9b88-a6ef79554e5a)
![image](https://github.com/ANHIG/IMGTHLA/assets/18323865/1f0cfb13-b45b-48dd-a5f6-9ee254579a3e)
