### ISSUE TITLE
Block of allele names with no associated sequences in the HLA-A protein alignment in release 3.55.0

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#358]
The last section of the [HLA-A protein alignment](https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/A_prot.txt) in release IPD-IMGT/HLA Database 3.55.0, above the 'appendix' peptide sequence for A*03:437Q at the end of the file, consists of rows for every allele, but shows no associated peptide sequence. 

This seems to suggest that none of these alleles has any sequence at peptide position 342, but A*03:437Q is included in this set of alleles with no sequence at position 342, and then appears at the end of the file with an Leucine peptide sequence at position 342.

<img width="1037" alt="Screenshot 2024-01-17 at 9 56 05 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/c987d65d-290d-495b-9a7e-34d364cda248">

<img width="244" alt="Screenshot 2024-01-17 at 10 30 39 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/04f833e5-5369-4454-8344-631f070799b5">

<img width="606" alt="Screenshot 2024-01-17 at 10 13 30 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/5314c516-904d-43cc-b27f-b34609e17034">

This seems like an error, but is it intentional? If so, what does it mean? If not, is it possible to regenerate this alignment without these additional lines?

**Comment by dominicbarkerAN** [comment]
Thank you for bringing this to our attention, the A_prot.txt and MICA_prot.txt have now been updated with this empty block removed.

**Comment by sjmack** [comment]
Thank you for addressing this so quickly!!
