### ISSUE TITLE
Discrepancy between TAP2 protein and nucleotide alignments

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#360]
I don't know what the proper term is for the extra peptide sequences that appear at the bottom of IPD-IMGT/HLA protein alignment documents due to frameshift mutations or nonstop mutations in native stop codons, but I call them 'appendices'. If you have a formal term for these, please let me know. 

I've attached some screenshots of the TAP2 nucleotide and protein alignments, specifically focused on these 'appendix' sequences.

In the nucleotide alignment, the main (prior to the 'appendix') alignment ends with codon 687, which is the TAG (amber) stop codon in the reference sequence.  In TAP2 alleles *02:01:01 to *02:05, TAG is changed to CAG, which encodes Glutamine (Q).

In the main sequence of the TAP2 nucleotide alignment, this CAG sequence is in the codon 687 position at the end of the last complete sequence block. 

![TAP2_nuc_alignment](https://github.com/ANHIG/IMGTHLA/assets/8935284/813ee9c2-b8e3-4412-af11-1f59850a9f26)

In the TAP2 peptide alignment, the 'appendix' sequence begins with amino acid residue 687, which is Q. 

![TAP2_prot_alignment_appendix](https://github.com/ANHIG/IMGTHLA/assets/8935284/67f1573f-8dcf-496a-b047-1671ef1ca5d9)

The 'appendix' sequences in the TAP2 nucleotide alignment also begin with codon 687, but this codon 687 has a GAG sequence, which encodes Glutamate (E).

![TAP2_nuc_alignment_appendix](https://github.com/ANHIG/IMGTHLA/assets/8935284/330fff8b-adad-4e6d-a4a3-0a950a9b5a27)

As you can see in the TAP2 'appendix' protein alignment, E is the sequence of residue 688.

The first codon of TAP2 nucleotide sequence 'appendix' seems to be incorrectly identified as codon 687, when it should be identified as codon 688.

In addition, the last nucleotide position in the main TAP2 alignment appears to be 2061, while the first nucleotide position in the TAP2 alignment 'appendix' is indicated as being position 2061. I don't know if this apparent discrepancy is related to the codon numbering discrepancy between the nucleotide and protein alignments.

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this issue to our attention. We agree that the numbering of codons for alleles which have sequence after the reference stop codon is inconsistent in TAP2 and are working to correct this and provide an updated file.

**Comment by dominicbarkerAN** [comment]
Hi Steven, sorry it took so long to update the TAP2 alignments to resolve this issue, this is now updated on 3550 and the Latest branch

**Comment by sjmack** [comment]
Thank you!
