### ISSUE TITLE
Discrepancy between the DPA1_prot.txt and DPA1_nuc.txt files for the DPA1*03:05:01Q alleles

### ISSUE THREAD

**Issue by RomuloVianna** [ANHIG/IMGTHLA#361]
There is a discrepancy between the DPA1_prot.txt and DPA1_nuc.txt files for the -DPA1"03:05:01Q alleles on v3.55. According to the alignment information for the protein obtained from the database (DPA1_prot.txt file), the first 6 amino acids present on the -DPA1"01:03:01 are not expressed in the -DPA1"03:05:01Q allele (deletions indicated as 6 dots) as displayed below:

![unnamed](https://github.com/ANHIG/IMGTHLA/assets/52458787/5f58ceb2-e8a4-4557-92e8-c9233ad3543a)

However, the information for the coding nucleotides alignment of -DPA1"03:05:01Q on the DPA1_nuc.txt file shows the first 6 codons as part of the exon 1 and not as deletions (dots) as shown for the protein alignment. 

![unnamed](https://github.com/ANHIG/IMGTHLA/assets/52458787/3719dce7-5d5e-4811-a101-6ee6554d28f1)

I assume that either DPA1_prot.txt or the DPA1_nuc.txt file should be adjusted so both agree on the same information of whether the first coding codon from the -DPA1"03:05:01Q alleles is ATG (on the seventh codon aligned to -DPA1"01:03:01) or ACG (as the first aligned to -DPA1"01:03:01).

**Comment by dominicbarkerAN** [comment]
Hello, the alleles you are describing, DPA1*03:05:01:01Q, DPA1*03:05:01:02Q and DPA1*03:05:02Q all contain mutations in the start codon, the ATG starting at position 1 of the cDNA is ACG in these alleles. These nucleotides are present in the sequence and included in their homologous positions in the CDS alignment. However the protein translation cannot start here, because the start codon is disrupted. The translation therefore starts at the next ATG beginning at position 19 in the cDNA. The 6 codons that are not translated are correctly marked up as deletions in the protein alignment. This happens in many other alleles in other genes, as well as DPA1*02:64Q in DPA1.

I hope this explanation answers your query.

**Comment by RomuloVianna** [comment]
Hi @dominicbarkerAN, thanks for your detailed reply!
Assuming what you said that the first 6 codons (ACG CGC CCT GAA GAC AGA) of -DPA1"03:05:01Q alleles are not translated, so we can say that **this is not a coding sequence**.
Also, considering that the files designated “X_nuc.txt”, where X is a locus or gene, contain the nucleotide **coding sequences** (CDS), shouldn't the first 6 codons be considered as a part of the 5'UTR region rather than a part of a coding sequence such as the exon 1?

**Comment by dominicbarkerAN** [comment]
Hi @RomuloVianna 

You are correct to say that these nucleotides are not translated and therefore not part of the coding sequence. However we include the homologous CDS regions of alleles with respect to the reference for that locus. For this reason we include nucleotides up to the canonical start codon even in cases where a mutation causes is to be disrupted. Similarly we include nucleotide sequence up to the canonical stop codon for alleles which have a premature stop. Polymorphisms can occur in these regions and need to be represented to prevent ambiguous typing results.

**Comment by RomuloVianna** [comment]
Hi again @dominicbarkerAN 

I am sorry if I am missing something here but I really don't get why aren't the first 6 codons (ACG CGC CCT GAA GAC AGA) of -DPA1"03:05:01:01Q represented as dots on the alignment for the **DPA1_nuc.txt** file as well as for example the -DRB4"01:03:01:02N is represented in the **DRB4_nuc.txt** file on the beggining of its exon 2 which starts a few nucleotides after the canonical start as discussed on https://github.com/ANHIG/IMGTHLA/issues/298

![image](https://github.com/ANHIG/IMGTHLA/assets/52458787/fef00a99-3f76-4775-9ddb-7e800b386f07)


Speaking of the -DRB4"01:03:01:02N allele, the genomic sequence contains nucleotides that match with the beginning of exon 2 in a homologous way but since they do not belong to the exon itself, I see that this region is not represented with the nucleotide letters but with dots instead (image above).

Going back to the -DPA1"03:05:01:01Q allele, I double-checked and the **hla.dat** file also confirms that the exon 1 start for the -DPA1"03:05:01:01Q is after the first 6 codons.

> FT   CDS             join(519..618,4203..4448,4789..5070,5285..5439)
