### ISSUE TITLE
The DPA1*01:05 allele is missing from the DPA1 genomic alignment. 

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#362]
I think the title says it all, but `DPA1*01:05` is present in the protein and cDNA/codon alignments, but is (inconspicuously) absent from the gDNA alignment. 

![image](https://github.com/ANHIG/IMGTHLA/assets/8935284/77c49ab1-07f8-450a-a112-fc1c6cb10572)

![image](https://github.com/ANHIG/IMGTHLA/assets/8935284/ae005312-b18a-414b-bb9a-a4819cda5eb7)

![image](https://github.com/ANHIG/IMGTHLA/assets/8935284/d737073c-52ab-408f-9a92-008df93caecb)

**Comment by sjmack** [comment]
I also note that `DOA*0104N` and `DPB1*73:01` are present in their respective protein and cDNA/codon alignments, but  absent from their genomic alignments. So perhaps there is something about the genomic alignments that requires that specific alleles be excluded?

**Comment by dominicbarkerAN** [comment]
Hi Steven, alleles are only included in the genomic alignments when the entire CDS and all intervening introns are submitted to the database. In the alignment you show, DPA1*01:05 can be seen to be partial at the CDS with unsequenced regions marked by *'s and so would not be included in the genomic alignments.

DPB1*73:01 is similarly partial and while DOA*01:04N has complete CDS sequence no intronic sequence has been submitted.

There are many thousands of alleles which do not have genomic sequence available.

If you are performing full gene sequencing and finding sequences for these alleles we encourage you to submit them to help reduce the number of unsequenced regions in the database.

**Comment by sjmack** [comment]
Thanks for explaining this. You learn something new everyday.
