### ISSUE TITLE
HLA-DOB*01:04:01:02 region annotation

### ISSUE THREAD

**Issue by marcellmarton** [ANHIG/IMGTHLA#367]
Hello!
The region annotation of HLA-DOB*01:04:01:02 is not updated except for the source region in the hla.dat file of 3550 branch. 
Can you fix this issue on 3550 and subsequent branches?
Thanks!

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this issue to our attention. You are correct that the sequence feature coordinates are not correctly updated for DOB*01:04:01:02 on the 3550 branch. This is correct in 3560 and has now been corrected for 3550.

**Comment by marcellmarton** [comment]
Thank you!
