### ISSUE TITLE
not found  HLA39951,DRB3*03:70  genomic sequence in  fasta folder

### ISSUE THREAD

**Issue by lidd77** [ANHIG/IMGTHLA#368]
Hey,
     I  find this allele  name "HLA39951,DRB3*03:70"  in  IMGTHLA_3.56/Allelelist.txt , but  there is no  its  allele genomic sequence in  IMGTHLA_3.56/fasta/DRB3_gen.fasta .  
   could you tell me why ?     not just this allele , I find so many allele name listed in   Allelelist.txt, but these allele genomic sequence not found in  fasta/*_gen.fasta .    

Expecting your reply !

**Comment by dominicbarkerAN** [comment]
Hello, the answer to your question is available on our FAQ [https://www.ebi.ac.uk/ipd/imgt/hla/about/help/faq/](https://www.ebi.ac.uk/ipd/imgt/hla/about/help/faq/).

**Comment by lidd77** [comment]
> Hello, the answer to your question is available on our FAQ https://www.ebi.ac.uk/ipd/imgt/hla/about/help/faq/.

sorry,  not found  the answer  ... could you tell us which  question  is my answer ? 

thank you very much !

**Comment by jrob119** [comment]
We do not have complete sequence for all alleles. In order for an allele to be included in the various gen.fasta file we require a single contigous sequence from the start codon to the stop codon including all intervening exons and introns.

**Comment by lidd77** [comment]
> We do not have complete sequence for all alleles. In order for an allele to be included in the various gen.fasta file we require a single contigous sequence from the start codon to the stop codon including all intervening exons and introns.

Hello,   DRB3*03:70 is in the Allelelist.txt , but  not in  DRB3_gene.fasta ... .could anyone know why ?  

Expecting your reply !

**Comment by jrob119** [comment]
The sequence for DRB3*03:70 is 801 bps in length and contains only the exon sequences, for it to be included in a *_gen.fasta file it would need to include the intron sequences as well, as previously stated. 

We do not include sequences without the required introns in the gen.fasta files, this is documented in the FAQs and the README files.

**Comment by lidd77** [comment]
> The sequence for DRB3*03:70 is 801 bps in length and contains only the exon sequences, for it to be included in a *_gen.fasta file it would need to include the intron sequences as well, as previously stated.
> 
> We do not include sequences without the required introns in the gen.fasta files, this is documented in the FAQs and the README files.

thank you  @jrob119 ,    so  if  one allele is not listed in gen.fasta ,  that means  we can get this allele's HLA typing via  some HLA typing tools  based on NGS ....  Is this right understanding ?

**Comment by jrob119** [comment]
The database lists all valid alleles, as the database has collected sequences for over 25 years the coverage in terms of sequence varies. The database provides a number of file formats with different levels of sequence coverage. How NGS typing tools handle this and the alleles included is up to the software developers. Though to meet many accreditation standards software should be capable of identifying all sequences listed in the database. 

For more information on the database files I suggest reading our README files, and the many papers we have published, that are listed on our main website.
