### ISSUE TITLE
how to use the latet IMGT to create PRG_MHC_GRCh38_withIMGT database  from HLA-LA typing tool  ?

### ISSUE THREAD

**Issue by lidd77** [ANHIG/IMGTHLA#369]
hello,

     I  am  using HLA-LA tool to do HLA typing , but  this tool  needs a  PRG_MHC_GRCh38_withIMGT database. 
     I want to create a  new  PGR with latest IMGT version , so someone knows how to create that  ?  

thank you !

**Comment by jrob119** [comment]
Any queries regarding for importing or building files for HLA-LA should be directed to the HLA-LA developers.
