### ISSUE TITLE
wmda rel_dna_ser.txt description

### ISSUE THREAD

**Issue by b1ackdog** [ANHIG/IMGTHLA#371]
I suggest linking or copying the description from https://hla.alleles.org/wmda/index.html.  There are 6 fields in the file as opposed to 5 referenced on [github](https://github.com/ANHIG/IMGTHLA/tree/Latest/wmda).

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this inconsistency to our attention. This has now been updated in our wmda documentation  on the 3560 and Latest branch
