### ISSUE TITLE
Typo in the URL for the /alignments directory in release/branch 3.17.0. 

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#373]
The URL for the ["alignments" directory for release/branch 3.17.0](https://github.com/ANHIG/IMGTHLA/tree/3170/aligments) contains a typo.

Instead of "alignments", the path contains **"aligments"**, making it impossible to find the directory programmatically.

3.17.10 is the only release/branch in which this occurs. 

I realize that this is a ten year old release, but I hope that this can be addressed. 

<img width="1653" alt="Screenshot 2024-06-14 at 11 11 49 PM" src="https://github.com/ANHIG/IMGTHLA/assets/8935284/c3561fea-26fe-405d-b010-b0541c9cffd6">

**Comment by jrob119** [comment]
All done

**Comment by sjmack** [comment]
Thank you for the quick response!
