### ISSUE TITLE
Incorrect id in  alignmentreference element

### ISSUE THREAD

**Issue by j-hn** [ANHIG/IMGTHLA#375]
Hi 
in 3.57.0 release (xml)
the AlignmnetReference element has the same incorrect id ("HLA02033" ) for each entry regardless of the Allele

cheers
John

**Comment by dominicbarkerAN** [comment]
Hi John,

Thank you for bringing this issue to our attention, this has now been corrected on the 3570 and Latest branch, I apologise for any inconcenience.
