### ISSUE TITLE
The nucleotide alignment for the HLA-R gene fragment includes extraneous AA codon lines 

### ISSUE THREAD

**Issue by sjmack** [ANHIG/IMGTHLA#377]
The nucleotide alignment for the *new* HLA-R gene fragment contains "AA codon" positions. However, since this gene is not expressed there is no protein alignment. Can these "AA codon" position lines be removed, so that the nucleotide alignment is comparable to the alignments of other gene fragments (e.g., HLA-Y, as shown below)?

![Screenshot 2024-07-09 at 2 42 46 PM](https://github.com/ANHIG/IMGTHLA/assets/8935284/8ff1af10-8d31-47dd-82f1-590bb5260c0a)

![Screenshot 2024-07-09 at 2 45 50 PM](https://github.com/ANHIG/IMGTHLA/assets/8935284/4818ebb3-74e3-47b8-a42b-1cfe1c8f4bc9)

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this issue to our attention, we agree that as a pseudogene fragment HLA-R should not have AA codon numbering. This has been updated on the 3.57.0 and the Latest branch.

**Comment by sjmack** [comment]
Thanks for addressing this quickly!
