### ISSUE TITLE
Duplicate sequences in hla_nuc.fasta

### ISSUE THREAD

**Issue by colinhercus** [ANHIG/IMGTHLA#381]
Over 4000 NUC sequences are duplicated. Here's a few
      2 >HLA:HLA00664
      2 >HLA:HLA00665
      2 >HLA:HLA00666
      2 >HLA:HLA00667
      2 >HLA:HLA00668
      2 >HLA:HLA00669
      2 >HLA:HLA00670
      2 >HLA:HLA00671
      2 >HLA:HLA00672
      2 >HLA:HLA00673

**Comment by dominicbarkerAN** [comment]
Hello, thank you for bringing this issue to our attention. We have now removed the duplicate entries from the hla_prot/nuc/gen.fasta files on the 3.57.0 and Latest branch.

Best regards,

Dominic

**Comment by colinhercus** [comment]
This problem also appears in the KIR database
