### ISSUE TITLE
Use of zip format for hla.dat & hla_gen.fasta

### ISSUE THREAD

**Issue by colinhercus** [ANHIG/IMGTHLA#384]
Hi,

The use of a Mac zip file means these zip files have an '__MACOSX' folder in the archive as well as the data file. This can cause issues and error messages on Linux where it often reports 'archive contains two files'

gunzip hla.dat.zip doesn't recognise the .zip suffix.

This works but gives an error
gunzip -c hla.dat.zip >hla.dat
**gzip: hla.dat.zip has more than one entry--rest ignored**

unzip inflates hla.dat and also creates the __MACOSX folder

There are also problems with some  programs we use that expect only a single file in gzip format.

Would it be possible for you to change to using gzip (.gz) rather than zip?

Thanks, Colin

**Comment by bmschoene** [comment]
Wouldn't it make more sense to just remove the _MACOSX folder?
That didn't use to be there in previous releases, I think?

If the file format is changed to .gz, we will need ample pre-warning and a testing branch, please.

**Comment by colinhercus** [comment]
But zip is a container format so it is still a container with one file rather than a single gzip'd file.

**Comment by dominicbarkerAN** [comment]
Hi Colin, thank you for bringing this issue to our attention. I have now removed the '__MACOSX' folders from the zip files on the 3570 and Latest branch. We will review our process of making these files to ensure they are consistent in future. I apologise for any issues this caused.

The standard format we use to compress these large files is to use zip which also works on Linux and it would be a significant change to many branches of the repository to change to gzip. For the foreseeable future we will continue to use zip but if this does change ample warning will be provided.

Thanks again for bringing the'__MACOSX' folder to our attention.
