### ISSUE TITLE
B_gen.txt region borders

### ISSUE THREAD

**Issue by marcellmarton** [ANHIG/IMGTHLA#386]
Hello!
The region borders in B_gen.txt are missing or in wrong position in branch 3570 and 3560 after intron6 compared to regions described in hla.dat.
Can you please inspect and fix the issue?
Thank you!

**Comment by dominicbarkerAN** [comment]
Hello, thank you for raising this issue. Unfortunately we have not been able to identify any issues with the boundary positions in the B_gen.txt or hla.dat.zip file. Could you please send us an example of an allele and boundary you have found as an issue so we can investigate further.

Best,

Dominic

**Comment by marcellmarton** [comment]
Sure, sorry I was not exact with the issue.
The allele I've noticed this is B*51:197. For me at least it seems that exon7, intron7, exon8 and UTR2 is not divided as it is described in hla.dat.

**Comment by dominicbarkerAN** [comment]
Thank you for the additional information. B*51:197 is a complex allele as it is a recombinant between HLA-B and HLA-C with the 5' part of the sequence belonging to HLA-B and the 3' becoming HLA-C. As such it is believed to have an expressed exon 8 which is correctly marked up in the hla.dat file.

The text alignments are intended as a human readable format and require some interpretation. The boundaries mark the homologous regions in the alignment compared to B*07:02:01:01 and may differ from the true boundary positions. This is done to maintain the quality of the alignment.

This is also the case for other alleles that are splice site variants such as B*15:01:01:02N where the homologous intron 2 sequence is included in the CDS as shown in the hla.dat file. However to maintain the consistency of the alignment a boundary is still included.

To obtain the accurate boundary positions for HLA alleles we recommend using one of the standardised formats such as the hla.dat or hla.xml files.

**Comment by marcellmarton** [comment]
Thank you for the explanation! Is there any way to indicate this in the hla.dat file? For example by adding a qualifier to the region?

**Comment by dominicbarkerAN** [comment]
Thank you for the suggestion. We consider carefully how we mark up complex features in the hla.dat files and when and what qualifiers are appropriate to use. In the case of B*51:197 we believe it's exon 8 sequence to be expressed and that the markup in the hla.dat file is correct. If the issue you are having is different mark up of boundary positions between the hla.dat file and text alignments, we do not recommend computationally parsing the text alignments. For computational parsing we recommend using a more standardised format such as the B_gen.msf file.

We are very happy to respond to feedback on qualifiers you think may be used in such  cases in the hla.dat file and may adopt these qualifiers if we think they are appropriate.
