### ISSUE TITLE
Major difference between v3.56.0 and v3.57.0

### ISSUE THREAD

**Issue by Stikus** [ANHIG/IMGTHLA#387]
Hello, we are using your database with HLA-typing tool xHLA (https://github.com/humanlongevity/HLA).

Base tool is not updated, but it produced fairly good results and have [script](https://github.com/humanlongevity/HLA/blob/master/data/script/batch.sh) for IMGT database update. We are using slightly modified version of this script with great success.

This tool has 2 result files - short (with only HLA's themselves) and full (with ranked predictions etc.)

Every IMGT update doesn't change the content of the short result (you can find test data here: https://github.com/humanlongevity/HLA/tree/master/tests):
```
A*01:01	A*02:01
B*13:02	B*37:01
C*06:02	C*06:02
DPB1*04:01	DPB1*04:01
DQB1*02:02	DQB1*05:01
DRB1*07:01	DRB1*10:01
```

But full result most of the time differs a little:

- Full result for `v3.55.0`:
```
type	full	total	good	rank
A*01:01	A*01:01:01:01;A*01:01:104;A*01:01:83	4	4	1
A*02:01	A*02:01:01:01;A*02:01:104;A*02:01:11;A*02:01:133;A*02:01:134;A*02:01:136;A*02:01:143;A*02:01:156;A*02:01:164;A*02:01:181;A*02:01:185;A*02:01:192;A*02:01:200;A*02:01:205;A*02:01:208;A*02:01:21;A*02:01:50;A*02:01:80;A*02:01:89;A*02:01:98	4	4	1
B*13:02	B*13:02:01:01;B*13:02:05;B*13:02:16;B*13:02:20;B*13:02:21;B*13:02:28;B*13:02:29	5	5	1
B*37:01	B*37:01:01:01;B*37:01:13;B*37:01:22;B*37:01:26;B*37:01:27	5	5	1
C*06:02	C*06:02:01:01;C*06:02:12;C*06:02:13;C*06:02:24;C*06:02:29;C*06:02:32;C*06:02:36;C*06:02:41;C*06:02:46;C*06:02:49;C*06:02:51;C*06:02:53;C*06:02:63;C*06:02:65;C*06:02:67;C*06:02:68;C*06:02:69;C*06:02:79;C*06:02:83;C*06:02:84;C*06:02:87;C*06:02:91;C*06:02:98	6	6	1
DPB1*04:01	DPB1*04:01:01:01	4	4	1
DQB1*02:02	DQB1*02:02:01:01;DQB1*02:02:15	4	4	1
DQB1*05:01	DQB1*05:01:01:01	4	4	1
DRB1*07:01	DRB1*07:01:01:01	4	4	1
DRB1*10:01	DRB1*10:01:01:01	4	4	1
```

- Difference between `v3.55.0` and `v3.56.0` (few new HLA's added, other lines were unchanged):

```
Test 2 (full) is FAILED. diff output:
6c6
< C*06:02	C*06:02:01:01;C*06:02:113;C*06:02:115;C*06:02:12;C*06:02:13;C*06:02:24;C*06:02:29;C*06:02:32;C*06:02:36;C*06:02:41;C*06:02:46;C*06:02:49;C*06:02:51;C*06:02:53;C*06:02:63;C*06:02:65;C*06:02:67;C*06:02:68;C*06:02:69;C*06:02:79;C*06:02:83;C*06:02:84;C*06:02:87;C*06:02:91;C*06:02:98	6	6	1
---
> C*06:02	C*06:02:01:01;C*06:02:12;C*06:02:13;C*06:02:24;C*06:02:29;C*06:02:32;C*06:02:36;C*06:02:41;C*06:02:46;C*06:02:49;C*06:02:51;C*06:02:53;C*06:02:63;C*06:02:65;C*06:02:67;C*06:02:68;C*06:02:69;C*06:02:79;C*06:02:83;C*06:02:84;C*06:02:87;C*06:02:91;C*06:02:98	6	6	1

```

But after last update we got major differences in full result (that's why I've created this issue):
- Difference between `v3.55.0` and `v3.57.0` (all `ClassI` lines have major changes):
```
Test 2 (full) is FAILED. diff output:
2,6c2,6
< A*01:01	A*01:01:13	6	5	2
< A*02:01	A*02:01:01:01;A*02:01:132;A*02:01:213;A*02:01:215	6	6	1
< B*13:02	B*13:02:01:01;B*13:02:24	5	5	1
< B*37:01	B*37:01:01:01	5	5	1
< C*06:02	C*06:02:01:01	6	6	1
---
> A*01:01	A*01:01:01:01;A*01:01:104;A*01:01:83	4	4	1
> A*02:01	A*02:01:01:01;A*02:01:104;A*02:01:11;A*02:01:133;A*02:01:134;A*02:01:136;A*02:01:143;A*02:01:156;A*02:01:164;A*02:01:181;A*02:01:185;A*02:01:192;A*02:01:200;A*02:01:205;A*02:01:208;A*02:01:21;A*02:01:50;A*02:01:80;A*02:01:89;A*02:01:98	4	4	1
> B*13:02	B*13:02:01:01;B*13:02:05;B*13:02:16;B*13:02:20;B*13:02:21;B*13:02:28;B*13:02:29	5	5	1
> B*37:01	B*37:01:01:01;B*37:01:13;B*37:01:22;B*37:01:26;B*37:01:27	5	5	1
> C*06:02	C*06:02:01:01;C*06:02:12;C*06:02:13;C*06:02:24;C*06:02:29;C*06:02:32;C*06:02:36;C*06:02:41;C*06:02:46;C*06:02:49;C*06:02:51;C*06:02:53;C*06:02:63;C*06:02:65;C*06:02:67;C*06:02:68;C*06:02:69;C*06:02:79;C*06:02:83;C*06:02:84;C*06:02:87;C*06:02:91;C*06:02:98	6	6	1

```

Due to the fact that main tool stayed unchanged, it leads us to IMGT difference, can you give us any hint or, maybe, this is a bug?

**Comment by jrob119** [comment]
Thanks for your query, we do not actively support third party software and I would suggest you contact them directly to see if they can help with the issue. 

However, in order to see if there is a potential explanation based on the files produced by the IPD-IMGT/HLA Database could you provide information or confirm what files you are using to upload the software. 

The script link suggests that you may be using the alignments/*_nuc.txt files, we strongly advise that these are not used as a data source, as they are subject to change to allow for human-readability and do not follow a recognised standard format like the fasta, msf and other files we produce.

**Comment by Stikus** [comment]
I understand that you don't support third party, but xHLA seems abandoned - only here у can find help, especially do to changes in IMGT.

You are correct - we're using `*_nuc.txt` files (as the script):

```sh
IMGT_VERSION=3.56.0
IMGTrefDirRoot=/ref/IMGTHLA
IMGTxHLADataDir=/ref/IMGTHLA/IMGTHLA-3.56.0-xHLA/data
IMGTURL="https://github.com/ANHIG/IMGTHLA/archive/refs/tags/v${IMGT_VERSION}-alpha.zip"

wget -q -N $IMGTURL -O $IMGTrefDirRoot/v${IMGT_VERSION}-alpha.zip
unzip -o -qq $IMGTrefDirRoot/v${IMGT_VERSION}-alpha.zip -d $IMGTrefDirRoot
rm "$IMGTrefDirRoot/v${IMGT_VERSION}-alpha.zip"
mkdir -p "$IMGTxHLADataDir/raw" "$IMGTxHLADataDir/align" "$IMGTxHLADataDir/nuc" "$IMGTxHLADataDir/temp" "$IMGTxHLADataDir/dna" "$IMGTxHLADataDir/exon
ln -s "$IMGTrefDirRoot/IMGTHLA-${IMGT_VERSION}-alpha/alignments" "$IMGTxHLADataDir/raw/alignments
find $IMGTxHLADataDir/raw/alignments/ -type f -name '*_nuc.txt' | parallel '$XHLA_SCRIPT_DIR/000.alignment.nuc.pl {} > $IMGTxHLADataDir/nuc/{/}'
find $IMGTxHLADataDir/nuc -name '[ABC]_*' -delete
find $IMGTxHLADataDir/nuc -type f -printf '%f\n' | parallel '$XHLA_SCRIPT_DIR/005.exon.pl $IMGTxHLADataDir/nuc/{} $IMGTxHLADataDir/exon/{.}.shift $IMGTxHLADataDir/exon/{.}.faa $IMGTxHLADataDir/dna/{.}.fna'
find $IMGTxHLADataDir/exon -type f -name '*.faa' -printf '%f\n' | perl -pe 's|.+/||; s/_nuc.faa//' | parallel '$XHLA_SCRIPT_DIR/006.split.pl $IMGTxHLADataDir/exon/{}_nuc.faa $IMGTxHLADataDir/temp/{} $IMGTxHLADataDir/align/{}.tsv'
cat $IMGTxHLADataDir/align/DQB*.tsv $IMGTxHLADataDir/align/DRB.tsv $IMGTxHLADataDir/align/DPB*.tsv $IMGTxHLADataDir/align/ClassI.tsv $DQB2tsvStr > $IMGTxHLADataDir/hla.unsorted.tsv
cat $IMGTxHLADataDir/exon/*.shift > $IMGTxHLADataDir/hla.shift
cat $IMGTxHLADataDir/exon/*.faa $DQB2faaStr > $IMGTxHLADataDir/hla.faa
sort -V $IMGTxHLADataDir/hla.unsorted.tsv > $IMGTxHLADataDir/hla.tsv
cat $IMGTxHLADataDir/dna/*.fna $DQB2fnaStr > $IMGTxHLADataDir/hla.fna
$DIAMOND makedb --in $IMGTxHLADataDir/hla.faa --db $IMGTxHLADataDir/hla.dmnd

```

`$DIAMOND` is a https://github.com/bbuchfink/diamond

**Comment by jrob119** [comment]
A known difference that may have an unexpected impact is that in 3.57.0 there is the extension of B*51:197 to include the full genomic sequence, which has a recombination with HLA-C, and so has exon 8 expressed. As we do not use the third party software we cannot confirm if this causes the an issue or how to mitigate for it.

**Comment by jrob119** [comment]
Also please note from our release emails;

As of release 3.56.0, all files provided at https://github.com/ANHIG/IMGTHLA are restricted in their maximum size. All large files (>100MB) are provided as compressed files rather than utilise Git LFS, which was previously required. This includes the hla.dat, xml/hla.xml and xml/hla_ambigs.xml. As of release 3.57.0 this now also includes the hla_gen.fasta file. We apologise for this enforced change, but the file size has increased faster than expected and we would rather include as a compressed file than drop the file entirely.
