### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by rleonid** [ANHIG/IMGTHLA#44]
Is there documentation for the txt alignment format (for example: [A_gen](https://github.com/jrob119/IMGTHLA/blob/Latest/alignments/A_gen.txt))?

Thank you for hosting this on github!

**Comment by ANHIG** [comment]
Please see http://www.ebi.ac.uk/ipd/imgt/hla/nomenclature/alignments.html, which details how the alignments are constructed and the conventions used.

**Comment by rleonid** [comment]
Thanks for the link! I was hoping there was more of a spec or even links to parsing code to use as a reference, but thanks for the good pointer.

**Comment by ANHIG** [comment]
Dear Leon

If you intend to parse these files, please be aware there are a number of other formats that may be more suitable, i.e. fasta, per , xml.

Many thanks

James Robinson

On 10 Feb 2016, at 17:46, Leonid Rozenberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for the link! I was hoping there was more of a spec or even links to parsing code to use as a reference, but thanks for the good pointer.

**Comment by rleonid** [comment]
I'm not familiar with the `per` or `xml` format, but those files are already conveniently aligned for you. Which is why I was asking about them.
