### ISSUE TITLE
What does '|' mean in the multiple sequence alignment?

### ISSUE THREAD

**Issue by mengyao** [ANHIG/IMGTHLA#63]
In the 'alignments' folder A_gen.txt file, there are several lines contain " | " symbol, for example:
 A_01:01:01:01     G | ATGGCCGTC ATGGCGCCCC GAACCCTCCT CCTGCTACTC TCGGGGGCCC TGGCCCTGAC CCAGACCTGG GCGG | GTGAGT GCGGGGTCGG GAGGGAAACC 
 A_01:01:01:02N    - | --------- ---------- ---------- ---------- ---------- ---------- ---------- ---- | ------ ---------- ---------- 
 A*01:01:01:03     \* | --------- ---------- ---------- ---------- ---------- ---------- ---------- ---- | ------ ---------- ----------  

May I ask what do these " | " symbols mean? 

Many thanks,

Mengyao

**Comment by ANHIG** [comment]
Many thanks for your query, a Readme file has been added to this directory.

**Comment by mengyao** [comment]
Hi,

Thank you very much for your quick help. 

Yours,

Mengyao

**Comment by mengyao** [comment]
Hi,

May I ask you two other questions?

In the README file, it states “The entry for each allele is displayed in respect to the reference sequences.”
1. In the gDNA alignment file, is the 1st haplotype for example “DQA1*01:01:01:01” the same as the reference sequence?
2. Which version of the human genome reference does the alignment correspond to? 
3. What’s the relationship between the coordinates labeled on the alignment and the human reference coordinate?

Many thanks,

Mengyao
