### ISSUE TITLE
miltiple sequence alignment reference

### ISSUE THREAD

**Issue by mengyao** [ANHIG/IMGTHLA#64]
Hi,
I see the list of the references of the multiple sequence alignment here:
http://www.ebi.ac.uk/ipd/imgt/hla/nomenclature/alignments.html
May I ask are the alleles in this list part of the human reference genome GRCh38?
Does GRCh38 contains all HLA genes?

Many thanks,

Mengyao

**Comment by ANHIG** [comment]
The references used are verified HLA allele sequences, and determined by the HLA Nomenclature Committee. These IPD-IMGT/HLA references sequences may be included in GRCh38, but we do not take data from GRCh38 for the entries in IPD-IMGT/HLA.

**Comment by mengyao** [comment]
Thank you for your reply.

Yours,

Mengyao
