### ISSUE TITLE
Errant A*11 allele in A_gen

### ISSUE THREAD

**Issue by rleonid** [ANHIG/IMGTHLA#76]
There is a misaligned A_11 file in A_gen, between A_32:86 and A*32:93.

**Comment by rleonid** [comment]
It looks like a merge of A_11:250 and A_23:01:01.

**Comment by ANHIG** [comment]
Can you please provide further details of the file this issue is seen in, is it the A_gen.txt, A_gen.fasta, A_gen.msf or A_gen.pir. Can you also list the allele entry (line number) you believe contains the issue?

**Comment by rleonid** [comment]
Line 3016 in A_gen.txt. Only `alignments/A_gen.txt`.

**Comment by ANHIG** [comment]
The A_11 text has been corrected to A_32:92N
