### ISSUE TITLE
DPA1_gen.fasta renamed to DPA_gen.fasta

### ISSUE THREAD

**Issue by rleonid** [ANHIG/IMGTHLA#81]
But the alignment file not renamed? The `pir` and `msf` files were also renamed.
Are sequences for the DPA2 pseudo gene forthcoming?
This isn't a technical issues just a consistency issue.

**Comment by ANHIG** [comment]
A number of files have been renamed to maintain consistency in naming standards

With regards to other pseudogenes, the HLA Informatics Group is actively looking at the sequences of a number of pseudogenes, both class I and class II, for inclusion into the IPD-IMGT/HLA database.
