### ISSUE TITLE
no newline following XML declaration in hla_ambigs.xml

### ISSUE THREAD

**Issue by jschneid-nmdp** [ANHIG/IMGTHLA#88]
On line 1 of hla_ambigs.xml, the XML declaration is not followed by a newline character, so the tns:ambiguityData start-tag appears on the same line.

A newline character is not required by the XML spec, but could be a helpful aesthetic enhancement.

**Comment by ANHIG** [comment]
This will be addressed in the forthcoming update


On 22 Dec 2016, at 17:46, Joel Schneider (NMDP) <notifications@github.com<mailto:notifications@github.com>> wrote:


On line 1 of hla_ambigs.xml, the XML declaration is not followed by a newline character, so the tns:ambiguityData start-tag appears on the same line.

A newline character is not required by the XML spec, but could be a helpful aesthetic enhancement.
