### ISSUE TITLE
Difference between fasta and alignments for A*01:11N

### ISSUE THREAD

**Issue by rleonid** [ANHIG/IMGTHLA#95]
One base pair before point mutation 968G>T, the sequences seem to diverge. The mutation (`T`) is higlighted:

From alignment file (that I think is correct):
GGAGAACGG**T**AA...
vs the fasta section:
GGAGAACGACCC...

**Comment by rleonid** [comment]
There seems to be a similar difference with B*07:44N.

**Comment by ANHIG** [comment]
The allele A\*01:11N contains an alternative splice site, there is 24 bps of sequence present in the genomic sequence that aligns to the end of exon 3. It is not translated in the CDS but is present genomic sequence. The representation of alleles like this B*07:44N  is marked up in the online version using shading, which cannot be done in the plain text files.

**Comment by ANHIG** [comment]
The alleles A\*01:11N, A\*03:01:01:02N, A\*29:01:01:02N, B\*07:44N, B\*15:01:01:02N and B*44:02:01:02S all contain alternative splice site for exons.

**Comment by rleonid** [comment]
Apologies, I should have been clearer. This is comparing `alignments/A_nuc.txt` vs `fasta/A_nuc.fasta`.

**Comment by ANHIG** [comment]
The latest release has more detailed documentation about the individual file formats. The 'nuc' files should only represent the sequence seen in the CDS and the 'gen' files all sequence. Only the online alignments should now contain sequence from splice variants in the CDS, and this should be marked up to indicate the sequence affected.

**Comment by rleonid** [comment]
Should an allele's sequence in `alignments/A_nuc.txt` and `fasta/A_nuc.fasta` be the same?
