### ISSUE TITLE
ClassI_nuc.txt alignment issue (extra insertion placeholders in B,C alleles cause misalignment)

### ISSUE THREAD

**Issue by dsoakley** [ANHIG/IMGTHLA#96]
Extra insertion place holders found in B and C alleles (not A) starting line 122460 causing the exon barrier to not align around  codon 182.

This looks like this A, B, and C got out of alignment due to an insertion placeholder present in the B alleles, but not A,C starting on line 98736 in B*07:02:01:01 (due to '-' symbol in B*40:345N, line 101665).

I can't attach the file, too big.

**Comment by ANHIG** [comment]
The file and the zip archive have been updated.
