### ISSUE TITLE
typos in README.md

### ISSUE THREAD

**Issue by jschneid-nmdp** [ANHIG/IMGTHLA#98]
It seems the COPYRIGHT NOTICE section of the README.md file here contains 1-2 typos.

The section indicates 2015 as the publication date for the Nucleic Acids Research article, but Google Scholar indicates 2014.  I think 2015 is a typo.

Another typo:  the word "stongly".

**Comment by ANHIG** [comment]
The Google Scholar entries incorrectly lists the publication date as 2015. The online publication date is 2014, but the  printed publication date is 2015 as listed.

**Comment by ANHIG** [comment]
A correction to the other typo has been submitted
